
INPUT_FILE = 'input/dorr_template.csv' # input template should match ATLAS below

OUTPUT_FOLDER = 'output/dorr_output'

# either 'DK', 'Destrieux', 'Tourville', 'Mice', 'Dorr', 'Dsurque' or 'Custom'
ATLAS = 'Dorr'

# either 'pial' (with gyri/sulci), 'inflated' (smooth) or 'white' (white-matter surface)
BRAIN_TYPE = 'pial'

# either cortical-outer, cortical-inner, subcortical 
# add -right-hemisphere or -left-hemisphere to end of image type to specify view
# image types "top" and "bottom" are available to show asymmetry
IMG_TYPE = 'top'

# what colours to use for showing brain pathology
# e.g. if the range of pathology is [0,3],
# then you need four colors (the first one is for pathology 0, i.e. no pathology)
# a pathology at 1.3 will interpolate between the second and third color

# NOTE: you can add more than 4 colours (as many as you want), in which case you should increase the range of the input biomarkers.
COLORS_RGB = [(1,1,1), (1,1,0), (1,0.4,0), (1,0,0)] # white -> yellow -> orange -> red
# COLORS_RGB = [(1,1,1), (1,0,0), (1,0,0), (1,0,0)] # white -> red -> red -> red

# output image resolution for X,Y in pixels
RESOLUTION = (1200, 900)

# default is white
BACKGROUND_COLOR = (1,1,1)

# to change camera viewing angle and other advanced settings, look into blendHelper.py:setCamera()
# for luminosity settings, look into blendHelper.py:setLamp()

if ATLAS == 'Mice' or ATLAS == 'Dorr' or ATLAS == 'Dsurque': 
    # we do not have white/inflated for mice yet
    BRAIN_TYPE = 'pial'



### Advanced settings, only change if you want to use custom atlas or if you'd like to not color at all some regions #####

# map the names of each 3D cortical structure to be coloured to the name of the structure you have in your atlas.
# only change the right-hand side values, as the left-hand side are used by blender.

# Common customisations:
# 1. to completely remove a region from being displayed, remove both the (key,value) pair.
# 2. to deactivate a region (always color it in default dark gray color), map its value to -1

# NOTE: Always make sure the RHS regions (dict values) below are present in your input .csv file.

### DK atlas ###

# Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
# disable any regions by setting its RHS to -1
cortAreasIndexMapDK = {
  'Right-bankssts':'Right-bankssts',
  'Right-caudalanteriorcingulate':'Right-caudalanteriorcingulate',
  'Right-caudalmiddlefrontal':'Right-caudalmiddlefrontal',
  'Right-cuneus':'Right-cuneus',
  'Right-entorhinal':'Right-entorhinal',
  'Right-frontalpole': 'Right-frontalpole',
  'Right-fusiform':'Right-fusiform',
  'Right-inferiorparietal':'Right-inferiorparietal',
  'Right-inferiortemporal':'Right-inferiortemporal',
  'Right-insula':'Right-insula',
  'Right-isthmuscingulate':'Right-isthmuscingulate',
  'Right-lateraloccipital':'Right-lateraloccipital',
  'Right-lateralorbitofrontal':'Right-lateralorbitofrontal',
  'Right-lingual':'Right-lingual',
  'Right-medialorbitofrontal':'Right-medialorbitofrontal',
  'Right-middletemporal':'Right-middletemporal',
  'Right-paracentral':'Right-paracentral',
  'Right-parahippocampal':'Right-parahippocampal',
  'Right-parsopercularis':'Right-parsopercularis',
  'Right-parsorbitalis':'Right-parsorbitalis',
  'Right-parstriangularis':'Right-parstriangularis',
  'Right-pericalcarine':'Right-pericalcarine',
  'Right-postcentral':'Right-postcentral',
  'Right-posteriorcingulate':'Right-posteriorcingulate',
  'Right-precentral':'Right-precentral',
  'Right-precuneus':'Right-precuneus',
  'Right-rostralanteriorcingulate':'Right-rostralanteriorcingulate',
  'Right-rostralmiddlefrontal':'Right-rostralmiddlefrontal',
  'Right-superiorfrontal':'Right-superiorfrontal',
  'Right-superiorparietal':'Right-superiorparietal',
  'Right-superiortemporal':'Right-superiortemporal',
  'Right-supramarginal':'Right-supramarginal',
  'Right-temporalpole':'Right-temporalpole',
  'Right-transversetemporal':'Right-transversetemporal',
  'Right-unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray
  
  'Left-bankssts':'Left-bankssts',
  'Left-caudalanteriorcingulate':'Left-caudalanteriorcingulate',
  'Left-caudalmiddlefrontal':'Left-caudalmiddlefrontal',
  'Left-cuneus':'Left-cuneus',
  'Left-entorhinal':'Left-entorhinal',
  'Left-frontalpole': 'Left-frontalpole',
  'Left-fusiform':'Left-fusiform',
  'Left-inferiorparietal':'Left-inferiorparietal',
  'Left-inferiortemporal':'Left-inferiortemporal',
  'Left-insula':'Left-insula',
  'Left-isthmuscingulate':'Left-isthmuscingulate',
  'Left-lateraloccipital':'Left-lateraloccipital',
  'Left-lateralorbitofrontal':'Left-lateralorbitofrontal',
  'Left-lingual':'Left-lingual',
  'Left-medialorbitofrontal':'Left-medialorbitofrontal',
  'Left-middletemporal':'Left-middletemporal',
  'Left-paracentral':'Left-paracentral',
  'Left-parahippocampal':'Left-parahippocampal',
  'Left-parsopercularis':'Left-parsopercularis',
  'Left-parsorbitalis':'Left-parsorbitalis',
  'Left-parstriangularis':'Left-parstriangularis',
  'Left-pericalcarine':'Left-pericalcarine',
  'Left-postcentral':'Left-postcentral',
  'Left-posteriorcingulate':'Left-posteriorcingulate',
  'Left-precentral':'Left-precentral',
  'Left-precuneus':'Left-precuneus',
  'Left-rostralanteriorcingulate':'Left-rostralanteriorcingulate',
  'Left-rostralmiddlefrontal':'Left-rostralmiddlefrontal',
  'Left-superiorfrontal':'Left-superiorfrontal',
  'Left-superiorparietal':'Left-superiorparietal',
  'Left-superiortemporal':'Left-superiortemporal',
  'Left-supramarginal':'Left-supramarginal',
  'Left-temporalpole':'Left-temporalpole',
  'Left-transversetemporal':'Left-transversetemporal',
  'Left-unknown':-1 # this is actually the middle region inside the cortical surface. color it as gray
}


### Destrieux atlas ###

# Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
cortAreasIndexMapDestrieux = {
    'Right-G_and_S_frontomargin': 'Right-G_and_S_frontomargin',
    'Right-G_and_S_occipital_inf': 'Right-G_and_S_occipital_inf',
    'Right-G_and_S_paracentral': 'Right-G_and_S_paracentral',
    'Right-G_and_S_subcentral': 'Right-G_and_S_subcentral',
    'Right-G_and_S_transv_frontopol': 'Right-G_and_S_transv_frontopol' ,
    'Right-G_and_S_cingul-Ant': 'Right-G_and_S_cingul-Ant',
    'Right-G_and_S_cingul-Mid-Ant': 'Right-G_and_S_cingul-Mid-Ant',
    'Right-G_and_S_cingul-Mid-Post': 'Right-G_and_S_cingul-Mid-Post',
    'Right-G_cingul-Post-dorsal': 'Right-G_cingul-Post-dorsal',
    'Right-G_cingul-Post-ventral': 'Right-G_cingul-Post-ventral',
    'Right-G_cuneus': 'Right-G_cuneus',
    'Right-G_front_inf-Opercular': 'Right-G_front_inf-Opercular',
    'Right-G_front_inf-Orbital': 'Right-G_front_inf-Orbital',
    'Right-G_front_inf-Triangul': 'Right-G_front_inf-Triangul' ,
    'Right-G_front_middle': 'Right-G_front_middle',
    'Right-G_front_sup': 'Right-G_front_sup',
    'Right-G_Ins_lg_and_S_cent_ins': 'Right-G_Ins_lg_and_S_cent_ins',
    'Right-G_insular_short': 'Right-G_insular_short',
    'Right-G_occipital_middle': 'Right-G_occipital_middle',
    'Right-G_occipital_sup': 'Right-G_occipital_sup',
    'Right-G_oc-temp_lat-fusifor': 'Right-G_oc-temp_lat-fusifor',
    'Right-G_oc-temp_med-Lingual': 'Right-G_oc-temp_med-Lingual' ,
    'Right-G_oc-temp_med-Parahip': 'Right-G_oc-temp_med-Parahip' ,
    'Right-G_orbital': 'Right-G_orbital',
    'Right-G_pariet_inf-Angular': 'Right-G_pariet_inf-Angular',
    'Right-G_pariet_inf-Supramar': 'Right-G_pariet_inf-Supramar',
    'Right-G_parietal_sup': 'Right-G_parietal_sup',
    'Right-G_postcentral': 'Right-G_postcentral',
    'Right-G_precentral': 'Right-G_precentral',
    'Right-G_precuneus': 'Right-G_precuneus',
    'Right-G_rectus': 'Right-G_rectus',
    'Right-G_subcallosal': 'Right-G_subcallosal',
    'Right-G_temp_sup-G_T_transv': 'Right-G_temp_sup-G_T_transv',
    'Right-G_temp_sup-Lateral': 'Right-G_temp_sup-Lateral',
    'Right-G_temp_sup-Plan_polar': 'Right-G_temp_sup-Plan_polar' ,
    'Right-G_temp_sup-Plan_tempo': 'Right-G_temp_sup-Plan_tempo' ,
    'Right-G_temporal_inf': 'Right-G_temporal_inf',
    'Right-G_temporal_middle': 'Right-G_temporal_middle',
    'Right-Lat_Fis-ant-Horizont': 'Right-Lat_Fis-ant-Horizont',
    'Right-Lat_Fis-ant-Vertical': 'Right-Lat_Fis-ant-Vertical',
    'Right-Lat_Fis-post': 'Right-Lat_Fis-post',
    'Right-Pole_occipital': 'Right-Pole_occipital',
    'Right-Pole_temporal': 'Right-Pole_temporal',
    'Right-S_calcarine': 'Right-S_calcarine',
    'Right-S_central': 'Right-S_central',
    'Right-S_cingul-Marginalis': 'Right-S_cingul-Marginalis',
    'Right-S_circular_insula_ant': 'Right-S_circular_insula_ant',
    'Right-S_circular_insula_inf': 'Right-S_circular_insula_inf',
    'Right-S_circular_insula_sup': 'Right-S_circular_insula_sup',
    'Right-S_collat_transv_ant': 'Right-S_collat_transv_ant',
    'Right-S_collat_transv_post': 'Right-S_collat_transv_post',
    'Right-S_front_inf': 'Right-S_front_inf',
    'Right-S_front_middle': 'Right-S_front_middle',
    'Right-S_front_sup': 'Right-S_front_sup',
    'Right-S_interm_prim-Jensen': 'Right-S_interm_prim-Jensen',
    'Right-S_intrapariet_and_P_trans': 'Right-S_intrapariet_and_P_trans',
    'Right-S_oc_middle_and_Lunatus': 'Right-S_oc_middle_and_Lunatus',
    'Right-S_oc_sup_and_transversal': 'Right-S_oc_sup_and_transversal',
    'Right-S_occipital_ant': 'Right-S_occipital_ant',
    'Right-S_oc-temp_lat': 'Right-S_oc-temp_lat',
    'Right-S_oc-temp_med_and_Lingual': 'Right-S_oc-temp_med_and_Lingual',
    'Right-S_orbital_lateral': 'Right-S_orbital_lateral',
    'Right-S_orbital_med-olfact': 'Right-S_orbital_med-olfact',
    'Right-S_orbital-H_Shaped': 'Right-S_orbital-H_Shaped',
    'Right-S_parieto_occipital': 'Right-S_parieto_occipital',
    'Right-S_pericallosal': 'Right-S_pericallosal',
    'Right-S_postcentral': 'Right-S_postcentral',
    'Right-S_precentral-inf-part': 'Right-S_precentral-inf-part',
    'Right-S_precentral-sup-part': 'Right-S_precentral-sup-part',
    'Right-S_suborbital': 'Right-S_suborbital',
    'Right-S_subparietal': 'Right-S_subparietal',
    'Right-S_temporal_inf': 'Right-S_temporal_inf',
    'Right-S_temporal_sup': 'Right-S_temporal_sup',
    'Right-S_temporal_transverse': 'Right-S_temporal_transverse',
    'Right-Unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray


    'Left-G_and_S_frontomargin': 'Left-G_and_S_frontomargin',
    'Left-G_and_S_occipital_inf': 'Left-G_and_S_occipital_inf',
    'Left-G_and_S_paracentral': 'Left-G_and_S_paracentral',
    'Left-G_and_S_subcentral': 'Left-G_and_S_subcentral',
    'Left-G_and_S_transv_frontopol': 'Left-G_and_S_transv_frontopol' ,
    'Left-G_and_S_cingul-Ant': 'Left-G_and_S_cingul-Ant',
    'Left-G_and_S_cingul-Mid-Ant': 'Left-G_and_S_cingul-Mid-Ant',
    'Left-G_and_S_cingul-Mid-Post': 'Left-G_and_S_cingul-Mid-Post',
    'Left-G_cingul-Post-dorsal': 'Left-G_cingul-Post-dorsal',
    'Left-G_cingul-Post-ventral': 'Left-G_cingul-Post-ventral',
    'Left-G_cuneus': 'Left-G_cuneus',
    'Left-G_front_inf-Opercular': 'Left-G_front_inf-Opercular',
    'Left-G_front_inf-Orbital': 'Left-G_front_inf-Orbital',
    'Left-G_front_inf-Triangul': 'Left-G_front_inf-Triangul' ,
    'Left-G_front_middle': 'Left-G_front_middle',
    'Left-G_front_sup': 'Left-G_front_sup',
    'Left-G_Ins_lg_and_S_cent_ins': 'Left-G_Ins_lg_and_S_cent_ins',
    'Left-G_insular_short': 'Left-G_insular_short',
    'Left-G_occipital_middle': 'Left-G_occipital_middle',
    'Left-G_occipital_sup': 'Left-G_occipital_sup',
    'Left-G_oc-temp_lat-fusifor': 'Left-G_oc-temp_lat-fusifor',
    'Left-G_oc-temp_med-Lingual': 'Left-G_oc-temp_med-Lingual' ,
    'Left-G_oc-temp_med-Parahip': 'Left-G_oc-temp_med-Parahip' ,
    'Left-G_orbital': 'Left-G_orbital',
    'Left-G_pariet_inf-Angular': 'Left-G_pariet_inf-Angular',
    'Left-G_pariet_inf-Supramar': 'Left-G_pariet_inf-Supramar',
    'Left-G_parietal_sup': 'Left-G_parietal_sup',
    'Left-G_postcentral': 'Left-G_postcentral',
    'Left-G_precentral': 'Left-G_precentral',
    'Left-G_precuneus': 'Left-G_precuneus',
    'Left-G_rectus': 'Left-G_rectus',
    'Left-G_subcallosal': 'Left-G_subcallosal',
    'Left-G_temp_sup-G_T_transv': 'Left-G_temp_sup-G_T_transv',
    'Left-G_temp_sup-Lateral': 'Left-G_temp_sup-Lateral',
    'Left-G_temp_sup-Plan_polar': 'Left-G_temp_sup-Plan_polar' ,
    'Left-G_temp_sup-Plan_tempo': 'Left-G_temp_sup-Plan_tempo' ,
    'Left-G_temporal_inf': 'Left-G_temporal_inf',
    'Left-G_temporal_middle': 'Left-G_temporal_middle',
    'Left-Lat_Fis-ant-Horizont': 'Left-Lat_Fis-ant-Horizont',
    'Left-Lat_Fis-ant-Vertical': 'Left-Lat_Fis-ant-Vertical',
    'Left-Lat_Fis-post': 'Left-Lat_Fis-post',
    'Left-Pole_occipital': 'Left-Pole_occipital',
    'Left-Pole_temporal': 'Left-Pole_temporal',
    'Left-S_calcarine': 'Left-S_calcarine',
    'Left-S_central': 'Left-S_central',
    'Left-S_cingul-Marginalis': 'Left-S_cingul-Marginalis',
    'Left-S_circular_insula_ant': 'Left-S_circular_insula_ant',
    'Left-S_circular_insula_inf': 'Left-S_circular_insula_inf',
    'Left-S_circular_insula_sup': 'Left-S_circular_insula_sup',
    'Left-S_collat_transv_ant': 'Left-S_collat_transv_ant',
    'Left-S_collat_transv_post': 'Left-S_collat_transv_post',
    'Left-S_front_inf': 'Left-S_front_inf',
    'Left-S_front_middle': 'Left-S_front_middle',
    'Left-S_front_sup': 'Left-S_front_sup',
    'Left-S_interm_prim-Jensen': 'Left-S_interm_prim-Jensen',
    'Left-S_intrapariet_and_P_trans': 'Left-S_intrapariet_and_P_trans',
    'Left-S_oc_middle_and_Lunatus': 'Left-S_oc_middle_and_Lunatus',
    'Left-S_oc_sup_and_transversal': 'Left-S_oc_sup_and_transversal',
    'Left-S_occipital_ant': 'Left-S_occipital_ant',
    'Left-S_oc-temp_lat': 'Left-S_oc-temp_lat',
    'Left-S_oc-temp_med_and_Lingual': 'Left-S_oc-temp_med_and_Lingual',
    'Left-S_orbital_lateral': 'Left-S_orbital_lateral',
    'Left-S_orbital_med-olfact': 'Left-S_orbital_med-olfact',
    'Left-S_orbital-H_Shaped': 'Left-S_orbital-H_Shaped',
    'Left-S_parieto_occipital': 'Left-S_parieto_occipital',
    'Left-S_pericallosal': 'Left-S_pericallosal',
    'Left-S_postcentral': 'Left-S_postcentral',
    'Left-S_precentral-inf-part': 'Left-S_precentral-inf-part',
    'Left-S_precentral-sup-part': 'Left-S_precentral-sup-part',
    'Left-S_suborbital': 'Left-S_suborbital',
    'Left-S_subparietal': 'Left-S_subparietal',
    'Left-S_temporal_inf': 'Left-S_temporal_inf',
    'Left-S_temporal_sup': 'Left-S_temporal_sup',
    'Left-S_temporal_transverse': 'Left-S_temporal_transverse',
    'Left-Unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray
}

### Mouse brain atlas ###

# Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
cortAreasIndexMapMice = {
  'Right-Anterior-cingulate': 'Right-Anterior-cingulate',
  'Right-Auditory': 'Right-Auditory',
  'Right-Cortical-subplate': 'Right-Cortical-subplate',
  'Right-Gustatory': 'Right-Gustatory',
  'Right-Infralimbic': 'Right-Infralimbic',
  'Right-Medulla': 'Right-Medulla',
  'Right-Olfactory': 'Right-Olfactory',
  'Right-Pons': 'Right-Pons',
  'Right-Prelimbic': 'Right-Prelimbic',
  'Right-Retrosplenial': 'Right-Retrosplenial',
  'Right-Somatomotor': 'Right-Somatomotor',
  'Right-Somatosensory': 'Right-Somatosensory',
  'Right-Striatum': 'Right-Striatum',
  'Right-Visceral': 'Right-Visceral',
  'Right-Visual': 'Right-Visual', 
  'Right-Agranular-insular-area': 'Right-Agranular-insular-area', 
  'Right-Posterior-parietal-association-areas': 'Right-Posterior-parietal-association-areas', 
  'Right-Temporal-association-areas': 'Right-Temporal-association-areas',
  'Right-Perirhinal': 'Right-Perirhinal',
  'Right-Ectorhinal': 'Right-Ectorhinal',

  'Left-Anterior-cingulate': 'Left-Anterior-cingulate',
  'Left-Auditory': 'Left-Auditory',
  'Left-Cortical-subplate': 'Left-Cortical-subplate',
  'Left-Gustatory': 'Left-Gustatory',
  'Left-Infralimbic': 'Left-Infralimbic',
  'Left-Medulla': 'Left-Medulla',
  'Left-Olfactory': 'Left-Olfactory',
  'Left-Pons': 'Left-Pons',
  'Left-Prelimbic': 'Left-Prelimbic',
  'Left-Retrosplenial': 'Left-Retrosplenial',
  'Left-Somatomotor': 'Left-Somatomotor',
  'Left-Somatosensory': 'Left-Somatosensory',
  'Left-Striatum': 'Left-Striatum',
  'Left-Visceral': 'Left-Visceral',
  'Left-Visual': 'Left-Visual', 
  'Left-Agranular-insular-area': 'Left-Agranular-insular-area', 
  'Left-Posterior-parietal-association-areas': 'Left-Posterior-parietal-association-areas', 
  'Left-Temporal-association-areas': 'Left-Temporal-association-areas',
  'Left-Perirhinal': 'Left-Perirhinal',
  'Left-Ectorhinal': 'Left-Ectorhinal',
}

# subcortical areas for mouse atlas
subcortMouseAreasIndexMap = {
  'Left-Cerebellum':'Left-Cerebellum', # -1 means do not colour this region
  'Left-Hypothalamus':'Left-Hypothalamus',
  'Left-Frontal-pole': 'Left-Frontal-pole', # Acronym for Frontal pole, cerebral cortex,
  'Left-Hippocampus': 'Left-Hippocampus',
  'Left-Midbrain':'Left-Midbrain',
  'Left-Pallidum': 'Left-Pallidum',
  'Left-Thalamus':'Left-Thalamus',

  'Right-Cerebellum':'Right-Cerebellum', # -1 means do not colour this region
  'Right-Hypothalamus':'Right-Hypothalamus',
  'Right-Frontal-pole': 'Right-Frontal-pole', # Acronym for Frontal pole, cerebral cortex,
  'Right-Hippocampus': 'Right-Hippocampus',
  'Right-Midbrain':'Right-Midbrain',
  'Right-Pallidum': 'Right-Pallidum',
  'Right-Thalamus':'Right-Thalamus'
}

# subcortical regions for the dorr atlas
subcortDorrAreasIndexMap = {
  'bilateral_cerebral_aqueduct': 'bilateral_cerebral_aqueduct',
  'bilateral_fourth_ventricle': 'bilateral_fourth_ventricle',
  'bilateral_interpedunclar_nucleus': 'bilateral_interpedunclar_nucleus',
  'bilateral_medulla': 'bilateral_medulla',
  'bilateral_midbrain': 'bilateral_midbrain',
  'bilateral_periaqueductal_grey': 'bilateral_periaqueductal_grey',
  'bilateral_pons': 'bilateral_pons',
  'bilateral_posterior_commissure': 'bilateral_posterior_commissure',
  'bilateral_third_ventricle': 'bilateral_third_ventricle',
  'bilateral_ventral_tegmental_decussation': 'bilateral_ventral_tegmental_decussation',
}

# subcortical regions for the dsurque atlas
subcortDsurqueAreasIndexMap = {
  'bilateral_cerebral_aqueduct': 'bilateral_cerebral_aqueduct',
  'bilateral_fourth_ventricle': 'bilateral_fourth_ventricle',
  'bilateral_interpedunclar_nucleus': 'bilateral_interpedunclar_nucleus',
  'bilateral_lobule_10_nodulus': 'bilateral_lobule_10_nodulus',
  'bilateral_lobule_10_white_matter': 'bilateral_lobule_10_white_matter',
  'bilateral_lobule_1_2_white_matter': 'bilateral_lobule_1_2_white_matter',
  'bilateral_lobule_3_central_lobule_dorsal': 'bilateral_lobule_3_central_lobule_dorsal',
  'bilateral_lobule_3_white_matter': 'bilateral_lobule_3_white_matter',
  'bilateral_lobule_6_declive': 'bilateral_lobule_6_declive',
  'bilateral_lobule_7_tuber_or_folium': 'bilateral_lobule_7_tuber_or_folium',
  'bilateral_lobule_8_pyramis': 'bilateral_lobule_8_pyramis',
  'bilateral_lobule_8_white_matter': 'bilateral_lobule_8_white_matter',
  'bilateral_lobule_9_uvula': 'bilateral_lobule_9_uvula',
  'bilateral_lobule_9_white_matter': 'bilateral_lobule_9_white_matter',
  'bilateral_lobules_1_2_lingula_and_central_lobule_ventral': 'bilateral_lobules_1_2_lingula_and_central_lobule_ventral',
  'bilateral_lobules_4_5_culmen_ventral_and_dorsal': 'bilateral_lobules_4_5_culmen_ventral_and_dorsal',
  'bilateral_lobules_4_5_white_matter': 'bilateral_lobules_4_5_white_matter',
  'bilateral_lobules_6_7_white_matter': 'bilateral_lobules_6_7_white_matter',
  'bilateral_medulla': 'bilateral_medulla',
  'bilateral_midbrain': 'bilateral_midbrain',
  'bilateral_periaqueductal_grey': 'bilateral_periaqueductal_grey',
  'bilateral_pons': 'bilateral_pons',
  'bilateral_posterior_commissure': 'bilateral_posterior_commissure',
  'bilateral_third_ventricle': 'bilateral_third_ventricle',
  'bilateral_trunk_of_arbor_vita': 'bilateral_trunk_of_arbor_vita',
  'bilateral_trunk_of_lobules_1_3_white_matter': 'bilateral_trunk_of_lobules_1_3_white_matter',
  'bilateral_trunk_of_lobules_6_8_white_matter': 'bilateral_trunk_of_lobules_6_8_white_matter',
  'bilateral_ventral_tegmental_decussation': 'bilateral_ventral_tegmental_decussation',
}

cortAreasIndexMapDsurque = {
  'Left_accessory_olfactory_bulb_glomerular_external_plexiform_and_mitral_cell_layer': 'Left_accessory_olfactory_bulb_glomerular_external_plexiform_and_mitral_cell_layer',
  'Left_accessory_olfdactory_bulb_granule_cell_layer': 'Left_accessory_olfactory_bulb_granule_cell_layer',
  'Left_amygdala': 'Left_amygdala',
  'Left_amygdalopiriform_transition_area': 'Left_amygdalopiriform_transition_area',
  'Left_anterior_commissure_pars_anterior': 'Left_anterior_commissure_pars_anterior',
  'Left_anterior_commissure_pars_posterior': 'Left_anterior_commissure_pars_posterior',
  'Left_anterior_lobule_lobules_4_5': 'Left_anterior_lobule_lobules_4_5',
  'Left_anterior_lobule_white_matter': 'Left_anterior_lobule_white_matter',
  'Left_anterior_olfactory_nucleus': 'Left_anterior_olfactory_nucleus',
  'Left_basal_forebrain': 'Left_basal_forebrain',
  'Left_bed_nucleus_of_stria_terminalis': 'Left_bed_nucleus_of_stria_terminalis',
  'Left_ca10r': 'Left_ca10r',
  'Left_ca1py': 'Left_ca1py',
  'Left_ca1rad': 'Left_ca1rad',
  'Left_ca20r': 'Left_ca20r',
  'Left_ca2py': 'Left_ca2py',
  'Left_ca2rad': 'Left_ca2rad',
  'Left_ca30r': 'Left_ca30r',
  'Left_ca3py_inner': 'Left_ca3py_inner',
  'Left_ca3py_outer': 'Left_ca3py_outer',
  'Left_ca3rad': 'Left_ca3rad',
  'Left_caudomedial_entorhinal_cortex': 'Left_caudomedial_entorhinal_cortex',
  'Left_cerebellar_peduncle_inferior': 'Left_cerebellar_peduncle_inferior',
  'Left_cerebellar_peduncle_middle': 'Left_cerebellar_peduncle_middle',
  'Left_cerebellar_peduncle_superior': 'Left_cerebellar_peduncle_superior',
  'Left_cerebral_peduncle': 'Left_cerebral_peduncle',
  'Left_cingulate_cortex_area_24a': 'Left_cingulate_cortex_area_24a',
  'Left_cingulate_cortex_area_24a_2': 'Left_cingulate_cortex_area_24a_2',
  'Left_cingulate_cortex_area_24b': 'Left_cingulate_cortex_area_24b',
  'Left_cingulate_cortex_area_24b_2': 'Left_cingulate_cortex_area_24b_2',
  'Left_cingulate_cortex_area_25': 'Left_cingulate_cortex_area_25',
  'Left_cingulate_cortex_area_29a': 'Left_cingulate_cortex_area_29a',
  'Left_cingulate_cortex_area_29b': 'Left_cingulate_cortex_area_29b',
  'Left_cingulate_cortex_area_29c': 'Left_cingulate_cortex_area_29c',
  'Left_cingulate_cortex_area_30': 'Left_cingulate_cortex_area_30',
  'Left_cingulate_cortex_area_32': 'Left_cingulate_cortex_area_32',
  'Left_cingulum': 'Left_cingulum',
  'Left_claustrum': 'Left_claustrum',
  'Left_claustrum_dorsal_part': 'Left_claustrum_dorsal_part',
  'Left_claustrum_ventral_part': 'Left_claustrum_ventral_part',
  'Left_colliculus_inferior': 'Left_colliculus_inferior',
  'Left_colliculus_superior': 'Left_colliculus_superior',
  'Left_copula_pyramis_lobule_8': 'Left_copula_pyramis_lobule_8',
  'Left_copula_white_matter': 'Left_copula_white_matter',
  'Left_corpus_callosum': 'Left_corpus_callosum',
  'Left_cortex_amygdala_transition_zones': 'Left_cortex_amygdala_transition_zones',
  'Left_corticospinal_tract_pyramids': 'Left_corticospinal_tract_pyramids',
  'Left_crus_1_ansiform_lobule_lobule_6': 'Left_crus_1_ansiform_lobule_lobule_6',
  'Left_crus_1_white_matter': 'Left_crus_1_white_matter',
  'Left_crus_2_ansiform_lobule_lobule_7': 'Left_crus_2_ansiform_lobule_lobule_7',
  'Left_crus_2_white_matter': 'Left_crus_2_white_matter',
  'Left_cuneate_nucleus': 'Left_cuneate_nucleus',
  'Left_dentate_nucleus': 'Left_dentate_nucleus',
  'Left_dorsal_intermediate_entorhinal_cortex': 'Left_dorsal_intermediate_entorhinal_cortex',
  'Left_dorsal_nucleus_of_the_endopiriform': 'Left_dorsal_nucleus_of_the_endopiriform',
  'Left_dorsal_tenia_tecta': 'Left_dorsal_tenia_tecta',
  'Left_dorsolateral_entorhinal_cortex': 'Left_dorsolateral_entorhinal_cortex',
  'Left_dorsolateral_orbital_cortex': 'Left_dorsolateral_orbital_cortex',
  'Left_ectorhinal_cortex': 'Left_ectorhinal_cortex',
  'Left_facial_nerve_cranial_nerve_7': 'Left_facial_nerve_cranial_nerve_7',
  'Left_fasciculus_retroflexus': 'Left_fasciculus_retroflexus',
  'Left_fastigial_nucleus': 'Left_fastigial_nucleus',
  'Left_fimbria': 'Left_fimbria',
  'Left_flocculus_fl': 'Left_flocculus_fl',
  'Left_flocculus_white_matter': 'Left_flocculus_white_matter',
  'Left_fornix': 'Left_fornix',
  'Left_frontal_association_cortex': 'Left_frontal_association_cortex',
  'Left_frontal_cortex_area_3': 'Left_frontal_cortex_area_3',
  'Left_fundus_of_striatum': 'Left_fundus_of_striatum',
  'Left_globus_pallidus': 'Left_globus_pallidus',
  'Left_gr_dg': 'Left_gr_dg',
  'Left_habenular_commissure': 'Left_habenular_commissure',
  'Left_hypothalamus': 'Left_hypothalamus',
  'Left_inferior_olivary_complex': 'Left_inferior_olivary_complex',
  'Left_insular_region_not_subdivided': 'Left_insular_region_not_subdivided',
  'Left_intermediate_nucleus_of_the_endopiriform_claustrum': 'Left_intermediate_nucleus_of_the_endopiriform_claustrum',
  'Left_internal_capsule': 'Left_internal_capsule',
  'Left_l_mol': 'Left_l_mol',
  'Left_lateral_olfactory_tract': 'Left_lateral_olfactory_tract',
  'Left_lateral_orbital_cortex': 'Left_lateral_orbital_cortex',
  'Left_lateral_parietal_association_cortex': 'Left_lateral_parietal_association_cortex',
  'Left_lateral_septum': 'Left_lateral_septum',
  'Left_lateral_ventricle': 'Left_lateral_ventricle',
  'Left_mammillary_bodies': 'Left_mammillary_bodies',
  'Left_mammilothalamic_tract': 'Left_mammilothalamic_tract',
  'Left_medial_amygdala': 'Left_medial_amygdala',
  'Left_medial_entorhinal_cortex': 'Left_medial_entorhinal_cortex',
  'Left_medial_lemniscus_medial_longitudinal_fasciculus': 'Left_medial_lemniscus_medial_longitudinal_fasciculus',
  'Left_medial_orbital_cortex': 'Left_medial_orbital_cortex',
  'Left_medial_parietal_association_cortex': 'Left_medial_parietal_association_cortex',
  'Left_medial_preoptic_nucleus': 'Left_medial_preoptic_nucleus',
  'Left_medial_septum': 'Left_medial_septum',
  'Left_mo_dg_Right': 'Left_mo_dg_Right',
  'Left_nucleus_accumbens': 'Left_nucleus_accumbens',
  'Left_nucleus_interpositus': 'Left_nucleus_interpositus',
  'Left_olfactory_bulb_external_plexiform_layer': 'Left_olfactory_bulb_external_plexiform_layer',
  'Left_olfactory_bulb_glomerular_layer': 'Left_olfactory_bulb_glomerular_layer',
  'Left_olfactory_bulb_granule_cell_layer': 'Left_olfactory_bulb_granule_cell_layer',
  'Left_olfactory_bulb_internal_plexiform_layer': 'Left_olfactory_bulb_internal_plexiform_layer',
  'Left_olfactory_bulb_mitral_cell_layer': 'Left_olfactory_bulb_mitral_cell_layer',
  'Left_olfactory_peduncle': 'Left_olfactory_peduncle',
  'Left_olfactory_tubercle': 'Left_olfactory_tubercle',
  'Left_optic_tract': 'Left_optic_tract',
  'Left_paraflocculus_pfl': 'Left_paraflocculus_pfl',
  'Left_paraflocculus_white_matter': 'Left_paraflocculus_white_matter',
  'Left_paramedian_lobule': 'Left_paramedian_lobule',
  'Left_paramedian_lobule_lobule_7': 'Left_paramedian_lobule_lobule_7',
  'Left_parietal_cortex_posterior_area_rostral_part': 'Left_parietal_cortex_posterior_area_rostral_part',
  'Left_perirhinal_cortex': 'Left_perirhinal_cortex',
  'Left_piriform_cortex': 'Left_piriform_cortex',
  'Left_po_dg': 'Left_po_dg',
  'Left_pontine_nucleus': 'Left_pontine_nucleus',
  'Left_posterolateral_cortical_amygdaloid_area': 'Left_posterolateral_cortical_amygdaloid_area',
  'Left_posteromedial_cortical_amygdaloid_area': 'Left_posteromedial_cortical_amygdaloid_area',
  'Left_pre_para_subiculum': 'Left_pre_para_subiculum',
  'Left_primary_auditory_cortex': 'Left_primary_auditory_cortex',
  'Left_primary_motor_cortex': 'Left_primary_motor_cortex',
  'Left_primary_somatosensory_cortex': 'Left_primary_somatosensory_cortex',
  'Left_primary_somatosensory_cortex_barrel_field': 'Left_primary_somatosensory_cortex_barrel_field',
  'Left_primary_somatosensory_cortex_dysgranular_zone': 'Left_primary_somatosensory_cortex_dysgranular_zone',
  'Left_primary_somatosensory_cortex_forelimb_region': 'Left_primary_somatosensory_cortex_forelimb_region',
  'Left_primary_somatosensory_cortex_hindlimb_region': 'Left_primary_somatosensory_cortex_hindlimb_region',
  'Left_primary_somatosensory_cortex_jaw_region': 'Left_primary_somatosensory_cortex_jaw_region',
  'Left_primary_somatosensory_cortex_shoulder_region': 'Left_primary_somatosensory_cortex_shoulder_region',
  'Left_primary_somatosensory_cortex_trunk_region': 'Left_primary_somatosensory_cortex_trunk_region',
  'Left_primary_somatosensory_cortex_upper_lip_region': 'Left_primary_somatosensory_cortex_upper_lip_region',
  'Left_primary_visual_cortex': 'Left_primary_visual_cortex',
  'Left_primary_visual_cortex_binocular_area': 'Left_primary_visual_cortex_binocular_area',
  'Left_primary_visual_cortex_monocular_area': 'Left_primary_visual_cortex_monocular_area',
  'Left_rostral_amygdalopiriform_area': 'Left_rostral_amygdalopiriform_area',
  'Left_s_lu': 'Left_s_lu',
  'Left_secondary_auditory_cortex_dorsal_area': 'Left_secondary_auditory_cortex_dorsal_area',
  'Left_secondary_auditory_cortex_ventral_area': 'Left_secondary_auditory_cortex_ventral_area',
  'Left_secondary_motor_cortex': 'Left_secondary_motor_cortex',
  'Left_secondary_somatosensory_cortex': 'Left_secondary_somatosensory_cortex',
  'Left_secondary_visual_cortex_lateral_area': 'Left_secondary_visual_cortex_lateral_area',
  'Left_secondary_visual_cortex_mediolateral_area': 'Left_secondary_visual_cortex_mediolateral_area',
  'Left_secondary_visual_cortex_mediomedial_area': 'Left_secondary_visual_cortex_mediomedial_area',
  'Left_simple_lobule_lobule_6': 'Left_simple_lobule_lobule_6',
  'Left_simple_lobule_white_matter': 'Left_simple_lobule_white_matter',
  'Left_stria_medullaris': 'Left_stria_medullaris',
  'Left_stria_terminalis': 'Left_stria_terminalis',
  'Left_striatum': 'Left_striatum',
  'Left_subependymale_zone_rhinocele': 'Left_subependymale_zone_rhinocele',
  'Left_subiculum': 'Left_subiculum',
  'Left_superior_olivary_complex': 'Left_superior_olivary_complex',
  'Left_temporal_association_area': 'Left_temporal_association_area',
  'Left_thalamus': 'Left_thalamus',
  'Left_trunk_of_crus_2_and_paramedian_white_matter': 'Left_trunk_of_crus_2_and_paramedian_white_matter',
  'Left_trunk_of_simple_and_crus_1_white_matter': 'Left_trunk_of_simple_and_crus_1_white_matter',
  'Left_ventral_intermediate_entorhinal_cortex': 'Left_ventral_intermediate_entorhinal_cortex',
  'Left_ventral_nucleus_of_the_endopiriform_claustrum': 'Left_ventral_nucleus_of_the_endopiriform_claustrum',
  'Left_ventral_orbital_cortex': 'Left_ventral_orbital_cortex',
  'Left_ventral_tenia_tecta': 'Left_ventral_tenia_tecta',

  'Right_accessory_olfactory_bulb_glomerular_external_plexiform_and_mitral_cell_layer': 'Right_accessory_olfactory_bulb_glomerular_external_plexiform_and_mitral_cell_layer',
  'Right_accessory_olfactory_bulb_granule_cell_layer': 'Right_accessory_olfactory_bulb_granule_cell_layer',
  'Right_amygdala': 'Right_amygdala',
  'Right_amygdalopiriform_transition_area': 'Right_amygdalopiriform_transition_area',
  'Right_anterior_commissure_pars_anterior': 'Right_anterior_commissure_pars_anterior',
  'Right_anterior_commissure_pars_posterior': 'Right_anterior_commissure_pars_posterior',
  'Right_anterior_lobule_lobules_4_5': 'Right_anterior_lobule_lobules_4_5',
  'Right_anterior_lobule_white_matter': 'Right_anterior_lobule_white_matter',
  'Right_anterior_olfactory_nucleus': 'Right_anterior_olfactory_nucleus',
  'Right_basal_forebrain': 'Right_basal_forebrain',
  'Right_bed_nucleus_of_stria_terminalis': 'Right_bed_nucleus_of_stria_terminalis',
  'Right_ca10r': 'Right_ca10r',
  'Right_ca1py': 'Right_ca1py',
  'Right_ca1rad': 'Right_ca1rad',
  'Right_ca20r': 'Right_ca20r',
  'Right_ca2py': 'Right_ca2py',
  'Right_ca2rad': 'Right_ca2rad',
  'Right_ca30r': 'Right_ca30r',
  'Right_ca3py_inner': 'Right_ca3py_inner',
  'Right_ca3py_outer': 'Right_ca3py_outer',
  'Right_ca3rad': 'Right_ca3rad',
  'Right_caudomedial_entorhinal_cortex': 'Right_caudomedial_entorhinal_cortex',
  'Right_cerebellar_peduncle_inferior': 'Right_cerebellar_peduncle_inferior',
  'Right_cerebellar_peduncle_middle': 'Right_cerebellar_peduncle_middle',
  'Right_cerebellar_peduncle_superior': 'Right_cerebellar_peduncle_superior',
  'Right_cerebral_peduncle': 'Right_cerebral_peduncle',
  'Right_cingulate_cortex_area_24a': 'Right_cingulate_cortex_area_24a',
  'Right_cingulate_cortex_area_24a_2': 'Right_cingulate_cortex_area_24a_2',
  'Right_cingulate_cortex_area_24b': 'Right_cingulate_cortex_area_24b',
  'Right_cingulate_cortex_area_24b_2': 'Right_cingulate_cortex_area_24b_2',
  'Right_cingulate_cortex_area_25': 'Right_cingulate_cortex_area_25',
  'Right_cingulate_cortex_area_29a': 'Right_cingulate_cortex_area_29a',
  'Right_cingulate_cortex_area_29b': 'Right_cingulate_cortex_area_29b',
  'Right_cingulate_cortex_area_29c': 'Right_cingulate_cortex_area_29c',
  'Right_cingulate_cortex_area_30': 'Right_cingulate_cortex_area_30',
  'Right_cingulate_cortex_area_32': 'Right_cingulate_cortex_area_32',
  'Right_cingulum': 'Right_cingulum',
  'Right_claustrum': 'Right_claustrum',
  'Right_claustrum_dorsal_part': 'Right_claustrum_dorsal_part',
  'Right_claustrum_ventral_part': 'Right_claustrum_ventral_part',
  'Right_colliculus_inferior': 'Right_colliculus_inferior',
  'Right_colliculus_superior': 'Right_colliculus_superior',
  'Right_copula_pyramis_lobule_8': 'Right_copula_pyramis_lobule_8',
  'Right_copula_white_matter': 'Right_copula_white_matter',
  'Right_corpus_callosum': 'Right_corpus_callosum',
  'Right_cortex_amygdala_transition_zones': 'Right_cortex_amygdala_transition_zones',
  'Right_corticospinal_tract_pyramids': 'Right_corticospinal_tract_pyramids',
  'Right_crus_1_ansiform_lobule_lobule_6': 'Right_crus_1_ansiform_lobule_lobule_6',
  'Right_crus_1_white_matter': 'Right_crus_1_white_matter',
  'Right_crus_2_ansiform_lobule_lobule_7': 'Right_crus_2_ansiform_lobule_lobule_7',
  'Right_crus_2_white_matter': 'Right_crus_2_white_matter',
  'Right_cuneate_nucleus': 'Right_cuneate_nucleus',
  'Right_dentate_nucleus': 'Right_dentate_nucleus',
  'Right_dorsal_intermediate_entorhinal_cortex': 'Right_dorsal_intermediate_entorhinal_cortex',
  'Right_dorsal_nucleus_of_the_endopiriform': 'Right_dorsal_nucleus_of_the_endopiriform',
  'Right_dorsal_tenia_tecta': 'Right_dorsal_tenia_tecta',
  'Right_dorsolateral_entorhinal_cortex': 'Right_dorsolateral_entorhinal_cortex',
  'Right_dorsolateral_orbital_cortex': 'Right_dorsolateral_orbital_cortex',
  'Right_ectorhinal_cortex': 'Right_ectorhinal_cortex',
  'Right_facial_nerve_cranial_nerve_7': 'Right_facial_nerve_cranial_nerve_7',
  'Right_fasciculus_retroflexus': 'Right_fasciculus_retroflexus',
  'Right_fastigial_nucleus': 'Right_fastigial_nucleus',
  'Right_fimbria': 'Right_fimbria',
  'Right_flocculus_fl': 'Right_flocculus_fl',
  'Right_flocculus_white_matter': 'Right_flocculus_white_matter',
  'Right_fornix': 'Right_fornix',
  'Right_frontal_association_cortex': 'Right_frontal_association_cortex',
  'Right_frontal_cortex_area_3': 'Right_frontal_cortex_area_3',
  'Right_fundus_of_striatum': 'Right_fundus_of_striatum',
  'Right_globus_pallidus': 'Right_globus_pallidus',
  'Right_gr_dg': 'Right_gr_dg',
  'Right_habenular_commissure': 'Right_habenular_commissure',
  'Right_hypothalamus': 'Right_hypothalamus',
  'Right_inferior_olivary_complex': 'Right_inferior_olivary_complex',
  'Right_insular_region_not_subdivided': 'Right_insular_region_not_subdivided',
  'Right_intermediate_nucleus_of_the_endopiriform_claustrum': 'Right_intermediate_nucleus_of_the_endopiriform_claustrum',
  'Right_internal_capsule': 'Right_internal_capsule',
  'Right_l_mol': 'Right_l_mol',
  'Right_lateral_olfactory_tract': 'Right_lateral_olfactory_tract',
  'Right_lateral_orbital_cortex': 'Right_lateral_orbital_cortex',
  'Right_lateral_parietal_association_cortex': 'Right_lateral_parietal_association_cortex',
  'Right_lateral_septum': 'Right_lateral_septum',
  'Right_lateral_ventricle': 'Right_lateral_ventricle',
  'Right_mammillary_bodies': 'Right_mammillary_bodies',
  'Right_mammilothalamic_tract': 'Right_mammilothalamic_tract',
  'Right_medial_amygdala': 'Right_medial_amygdala',
  'Right_medial_entorhinal_cortex': 'Right_medial_entorhinal_cortex',
  'Right_medial_lemniscus_medial_longitudinal_fasciculus': 'Right_medial_lemniscus_medial_longitudinal_fasciculus',
  'Right_medial_orbital_cortex': 'Right_medial_orbital_cortex',
  'Right_medial_parietal_association_cortex': 'Right_medial_parietal_association_cortex',
  'Right_medial_preoptic_nucleus': 'Right_medial_preoptic_nucleus',
  'Right_medial_septum': 'Right_medial_septum',
  'Right_mo_dg_Right': 'Right_mo_dg_Right',
  'Right_nucleus_accumbens': 'Right_nucleus_accumbens',
  'Right_nucleus_interpositus': 'Right_nucleus_interpositus',
  'Right_olfactory_bulb_external_plexiform_layer': 'Right_olfactory_bulb_external_plexiform_layer',
  'Right_olfactory_bulb_glomerular_layer': 'Right_olfactory_bulb_glomerular_layer',
  'Right_olfactory_bulb_granule_cell_layer': 'Right_olfactory_bulb_granule_cell_layer',
  'Right_olfactory_bulb_internal_plexiform_layer': 'Right_olfactory_bulb_internal_plexiform_layer',
  'Right_olfactory_bulb_mitral_cell_layer': 'Right_olfactory_bulb_mitral_cell_layer',
  'Right_olfactory_peduncle': 'Right_olfactory_peduncle',
  'Right_olfactory_tubercle': 'Right_olfactory_tubercle',
  'Right_optic_tract': 'Right_optic_tract',
  'Right_paraflocculus_pfl': 'Right_paraflocculus_pfl',
  'Right_paraflocculus_white_matter': 'Right_paraflocculus_white_matter',
  'Right_paramedian_lobule': 'Right_paramedian_lobule',
  'Right_paramedian_lobule_lobule_7': 'Right_paramedian_lobule_lobule_7',
  'Right_parietal_cortex_posterior_area_rostral_part': 'Right_parietal_cortex_posterior_area_rostral_part',
  'Right_perirhinal_cortex': 'Right_perirhinal_cortex',
  'Right_piriform_cortex': 'Right_piriform_cortex',
  'Right_po_dg': 'Right_po_dg',
  'Right_pontine_nucleus': 'Right_pontine_nucleus',
  'Right_posterolateral_cortical_amygdaloid_area': 'Right_posterolateral_cortical_amygdaloid_area',
  'Right_posteromedial_cortical_amygdaloid_area': 'Right_posteromedial_cortical_amygdaloid_area',
  'Right_pre_para_subiculum': 'Right_pre_para_subiculum',
  'Right_primary_auditory_cortex': 'Right_primary_auditory_cortex',
  'Right_primary_motor_cortex': 'Right_primary_motor_cortex',
  'Right_primary_somatosensory_cortex': 'Right_primary_somatosensory_cortex',
  'Right_primary_somatosensory_cortex_barrel_field': 'Right_primary_somatosensory_cortex_barrel_field',
  'Right_primary_somatosensory_cortex_dysgranular_zone': 'Right_primary_somatosensory_cortex_dysgranular_zone',
  'Right_primary_somatosensory_cortex_forelimb_region': 'Right_primary_somatosensory_cortex_forelimb_region',
  'Right_primary_somatosensory_cortex_hindlimb_region': 'Right_primary_somatosensory_cortex_hindlimb_region',
  'Right_primary_somatosensory_cortex_jaw_region': 'Right_primary_somatosensory_cortex_jaw_region',
  'Right_primary_somatosensory_cortex_shoulder_region': 'Right_primary_somatosensory_cortex_shoulder_region',
  'Right_primary_somatosensory_cortex_trunk_region': 'Right_primary_somatosensory_cortex_trunk_region',
  'Right_primary_somatosensory_cortex_upper_lip_region': 'Right_primary_somatosensory_cortex_upper_lip_region',
  'Right_primary_visual_cortex': 'Right_primary_visual_cortex',
  'Right_primary_visual_cortex_binocular_area': 'Right_primary_visual_cortex_binocular_area',
  'Right_primary_visual_cortex_monocular_area': 'Right_primary_visual_cortex_monocular_area',
  'Right_rostral_amygdalopiriform_area': 'Right_rostral_amygdalopiriform_area',
  'Right_s_lu': 'Right_s_lu',
  'Right_secondary_auditory_cortex_dorsal_area': 'Right_secondary_auditory_cortex_dorsal_area',
  'Right_secondary_auditory_cortex_ventral_area': 'Right_secondary_auditory_cortex_ventral_area',
  'Right_secondary_motor_cortex': 'Right_secondary_motor_cortex',
  'Right_secondary_somatosensory_cortex': 'Right_secondary_somatosensory_cortex',
  'Right_secondary_visual_cortex_lateral_area': 'Right_secondary_visual_cortex_lateral_area',
  'Right_secondary_visual_cortex_mediolateral_area': 'Right_secondary_visual_cortex_mediolateral_area',
  'Right_secondary_visual_cortex_mediomedial_area': 'Right_secondary_visual_cortex_mediomedial_area',
  'Right_simple_lobule_lobule_6': 'Right_simple_lobule_lobule_6',
  'Right_simple_lobule_white_matter': 'Right_simple_lobule_white_matter',
  'Right_stria_medullaris': 'Right_stria_medullaris',
  'Right_stria_terminalis': 'Right_stria_terminalis',
  'Right_striatum': 'Right_striatum',
  'Right_subependymale_zone_rhinocele': 'Right_subependymale_zone_rhinocele',
  'Right_subiculum': 'Right_subiculum',
  'Right_superior_olivary_complex': 'Right_superior_olivary_complex',
  'Right_temporal_association_area': 'Right_temporal_association_area',
  'Right_thalamus': 'Right_thalamus',
  'Right_trunk_of_crus_2_and_paramedian_white_matter': 'Right_trunk_of_crus_2_and_paramedian_white_matter',
  'Right_trunk_of_simple_and_crus_1_white_matter': 'Right_trunk_of_simple_and_crus_1_white_matter',
  'Right_ventral_intermediate_entorhinal_cortex': 'Right_ventral_intermediate_entorhinal_cortex',
  'Right_ventral_nucleus_of_the_endopiriform_claustrum': 'Right_ventral_nucleus_of_the_endopiriform_claustrum',
  'Right_ventral_orbital_cortex': 'Right_ventral_orbital_cortex',
  'Right_ventral_tenia_tecta': 'Right_ventral_tenia_tecta',
}

# Dorr areas for mouse atlas
cortAreasIndexMapDorr = {
  'Left_amygdala': 'Left_amygdala',
  'Left_anterior_commissure_pars_anterior': 'Left_anterior_commissure_pars_anterior',
  'Left_anterior_commissure_pars_posterior': 'Left_anterior_commissure_pars_posterior',
  'Left_arbor_vita_of_cerebellum': 'Left_arbor_vita_of_cerebellum',
  'Left_basal_forebrain': 'Left_basal_forebrain',
  'Left_bed_nucleus_of_stria_terminalis': 'Left_bed_nucleus_of_stria_terminalis',
  'Left_cerebellar_cortex': 'Left_cerebellar_cortex',
  'Left_cerebellar_peduncle_inferior': 'Left_cerebellar_peduncle_inferior',
  'Left_cerebellar_peduncle_middle': 'Left_cerebellar_peduncle_middle',
  'Left_cerebellar_peduncle_superior': 'Left_cerebellar_peduncle_superior',
  'Left_cerebral_cortex_entorhinal_cortex': 'Left_cerebral_cortex_entorhinal_cortex',
  'Left_cerebral_cortex_frontal_lobe': 'Left_cerebral_cortex_frontal_lobe',
  'Left_cerebral_cortex_occipital_lobe': 'Left_cerebral_cortex_occipital_lobe',
  'Left_cerebral_cortex_parieto_temporal_lobe': 'Left_cerebral_cortex_parieto_temporal_lobe',
  'Left_cerebral_peduncle': 'Left_cerebral_peduncle',
  'Left_colliculus_inferior': 'Left_colliculus_inferior',
  'Left_colliculus_superior': 'Left_colliculus_superior',
  'Left_corpus_callosum': 'Left_corpus_callosum',
  'Left_corticospinal_tract_pyramids': 'Left_corticospinal_tract_pyramids',
  'Left_cuneate_nucleus': 'Left_cuneate_nucleus',
  'Left_dentate_gyrus_of_hippocampus': 'Left_dentate_gyrus_of_hippocampus',
  'Left_facial_nerve_cranial_nerve_7': 'Left_facial_nerve_cranial_nerve_7',
  'Left_fasciculus_retroflexus': 'Left_fasciculus_retroflexus',
  'Left_fimbria': 'Left_fimbria',
  'Left_fornix': 'Left_fornix',
  'Left_fundus_of_striatum': 'Left_fundus_of_striatum',
  'Left_globus_pallidus': 'Left_globus_pallidus',
  'Left_habenular_commissure': 'Left_habenular_commissure',
  'Left_hippocampus': 'Left_hippocampus',
  'Left_hypothalamus': 'Left_hypothalamus',
  'Left_inferior_olivary_complex': 'Left_inferior_olivary_complex',
  'Left_internal_capsule': 'Left_internal_capsule',
  'Left_lateral_olfactory_tract': 'Left_lateral_olfactory_tract',
  'Left_lateral_septum': 'Left_lateral_septum',
  'Left_lateral_ventricle': 'Left_lateral_ventricle',
  'Left_mammillary_bodies': 'Left_mammillary_bodies',
  'Left_mammilothalamic_tract': 'Left_mammilothalamic_tract',
  'Left_medial_lemniscus_medial_longitudinal_fasciculus': 'Left_medial_lemniscus_medial_longitudinal_fasciculus',
  'Left_medial_septum': 'Left_medial_septum',
  'Left_nucleus_accumbens': 'Left_nucleus_accumbens',
  'Left_olfactory_bulbs': 'Left_olfactory_bulbs',
  'Left_olfactory_tubercle': 'Left_olfactory_tubercle',
  'Left_optic_tract': 'Left_optic_tract',
  'Left_pontine_nucleus': 'Left_pontine_nucleus',
  'Left_pre_para_subiculum': 'Left_pre_para_subiculum',
  'Left_stratum_granulosum_of_hippocampus': 'Left_stratum_granulosum_of_hippocampus',
  'Left_stria_medullaris': 'Left_stria_medullaris',
  'Left_stria_terminalis': 'Left_stria_terminalis',
  'Left_striatum': 'Left_striatum',
  'Left_subependymale_zone_rhinocele': 'Left_subependymale_zone_rhinocele',
  'Left_superior_olivary_complex': 'Left_superior_olivary_complex',
  'Left_thalamus': 'Left_thalamus',

  'Right_amygdala': 'Right_amygdala',
  'Right_anterior_commissure_pars_anterior': 'Right_anterior_commissure_pars_anterior',
  'Right_anterior_commissure_pars_posterior': 'Right_anterior_commissure_pars_posterior',
  'Right_arbor_vita_of_cerebellum': 'Right_arbor_vita_of_cerebellum',
  'Right_basal_forebrain': 'Right_basal_forebrain',
  'Right_bed_nucleus_of_stria_terminalis': 'Right_bed_nucleus_of_stria_terminalis',
  'Right_cerebellar_cortex': 'Right_cerebellar_cortex',
  'Right_cerebellar_peduncle_inferior': 'Right_cerebellar_peduncle_inferior',
  'Right_cerebellar_peduncle_middle': 'Right_cerebellar_peduncle_middle',
  'Right_cerebellar_peduncle_superior': 'Right_cerebellar_peduncle_superior',
  'Right_cerebral_cortex_entorhinal_cortex': 'Right_cerebral_cortex_entorhinal_cortex',
  'Right_cerebral_cortex_frontal_lobe': 'Right_cerebral_cortex_frontal_lobe',
  'Right_cerebral_cortex_occipital_lobe': 'Right_cerebral_cortex_occipital_lobe',
  'Right_cerebral_cortex_parieto_temporal_lobe': 'Right_cerebral_cortex_parieto_temporal_lobe',
  'Right_cerebral_peduncle': 'Right_cerebral_peduncle',
  'Right_colliculus_inferior': 'Right_colliculus_inferior',
  'Right_colliculus_superior': 'Right_colliculus_superior',
  'Right_corpus_callosum': 'Right_corpus_callosum',
  'Right_corticospinal_tract_pyramids': 'Right_corticospinal_tract_pyramids',
  'Right_cuneate_nucleus': 'Right_cuneate_nucleus',
  'Right_dentate_gyrus_of_hippocampus': 'Right_dentate_gyrus_of_hippocampus',
  'Right_facial_nerve_cranial_nerve_7': 'Right_facial_nerve_cranial_nerve_7',
  'Right_fasciculus_retroflexus': 'Right_fasciculus_retroflexus',
  'Right_fimbria': 'Right_fimbria',
  'Right_fornix': 'Right_fornix',
  'Right_fundus_of_striatum': 'Right_fundus_of_striatum',
  'Right_globus_pallidus': 'Right_globus_pallidus',
  'Right_habenular_commissure': 'Right_habenular_commissure',
  'Right_hippocampus': 'Right_hippocampus',
  'Right_hypothalamus': 'Right_hypothalamus',
  'Right_inferior_olivary_complex': 'Right_inferior_olivary_complex',
  'Right_internal_capsule': 'Right_internal_capsule',
  'Right_lateral_olfactory_tract': 'Right_lateral_olfactory_tract',
  'Right_lateral_septum': 'Right_lateral_septum',
  'Right_lateral_ventricle': 'Right_lateral_ventricle',
  'Right_mammillary_bodies': 'Right_mammillary_bodies',
  'Right_mammilothalamic_tract': 'Right_mammilothalamic_tract',
  'Right_medial_lemniscus_medial_longitudinal_fasciculus': 'Right_medial_lemniscus_medial_longitudinal_fasciculus',
  'Right_medial_septum': 'Right_medial_septum',
  'Right_nucleus_accumbens': 'Right_nucleus_accumbens',
  'Right_olfactory_bulbs': 'Right_olfactory_bulbs',
  'Right_olfactory_tubercle': 'Right_olfactory_tubercle',
  'Right_optic_tract': 'Right_optic_tract',
  'Right_pontine_nucleus': 'Right_pontine_nucleus',
  'Right_pre_para_subiculum': 'Right_pre_para_subiculum',
  'Right_stratum_granulosum_of_hippocampus': 'Right_stratum_granulosum_of_hippocampus',
  'Right_stria_medullaris': 'Right_stria_medullaris',
  'Right_stria_terminalis': 'Right_stria_terminalis',
  'Right_striatum': 'Right_striatum',
  'Right_subependymale_zone_rhinocele': 'Right_subependymale_zone_rhinocele',
  'Right_superior_olivary_complex': 'Right_superior_olivary_complex',
  'Right_thalamus': 'Right_thalamus',
}


### Tourville atlas ###

# Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
cortAreasIndexMapTourville = {
  'Right-caudalanteriorcingulate': 'Right-caudalanteriorcingulate',
  'Right-caudalmiddlefrontal': 'Right-caudalmiddlefrontal',
  'Right-cuneus': 'Right-cuneus',
  'Right-entorhinal': 'Right-entorhinal',
  'Right-fusiform': 'Right-fusiform',
  'Right-inferiorparietal': 'Right-inferiorparietal',
  'Right-inferiortemporal': 'Right-inferiortemporal',
  'Right-insula': 'Right-insula',
  'Right-isthmuscingulate': 'Right-isthmuscingulate',
  'Right-lateraloccipital': 'Right-lateraloccipital',
  'Right-lateralorbitofrontal': 'Right-lateralorbitofrontal',
  'Right-lingual': 'Right-lingual',
  'Right-medialorbitofrontal': 'Right-medialorbitofrontal',
  'Right-middletemporal': 'Right-middletemporal',
  'Right-paracentral': 'Right-paracentral',
  'Right-parahippocampal': 'Right-parahippocampal',
  'Right-parsopercularis': 'Right-parsopercularis',
  'Right-parsorbitalis': 'Right-parsorbitalis',
  'Right-parstriangularis': 'Right-parstriangularis',
  'Right-pericalcarine': 'Right-pericalcarine',
  'Right-postcentral': 'Right-postcentral',
  'Right-posteriorcingulate': 'Right-posteriorcingulate',
  'Right-precentral': 'Right-precentral',
  'Right-precuneus': 'Right-precuneus',
  'Right-rostralanteriorcingulate': 'Right-rostralanteriorcingulate',
  'Right-rostralmiddlefrontal': 'Right-rostralmiddlefrontal',
  'Right-superiorfrontal': 'Right-superiorfrontal',
  'Right-superiorparietal': 'Right-superiorparietal',
  'Right-superiortemporal': 'Right-superiortemporal',
  'Right-supramarginal': 'Right-supramarginal',
  'Right-transversetemporal': 'Right-transversetemporal',
  'Right-unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray

  'Left-caudalanteriorcingulate': 'Left-caudalanteriorcingulate',
  'Left-caudalmiddlefrontal': 'Left-caudalmiddlefrontal',
  'Left-cuneus': 'Left-cuneus',
  'Left-entorhinal': 'Left-entorhinal',
  'Left-fusiform': 'Left-fusiform',
  'Left-inferiorparietal': 'Left-inferiorparietal',
  'Left-inferiortemporal': 'Left-inferiortemporal',
  'Left-insula': 'Left-insula',
  'Left-isthmuscingulate': 'Left-isthmuscingulate',
  'Left-lateraloccipital': 'Left-lateraloccipital',
  'Left-lateralorbitofrontal': 'Left-lateralorbitofrontal',
  'Left-lingual': 'Left-lingual',
  'Left-medialorbitofrontal': 'Left-medialorbitofrontal',
  'Left-middletemporal': 'Left-middletemporal',
  'Left-paracentral': 'Left-paracentral',
  'Left-parahippocampal': 'Left-parahippocampal',
  'Left-parsopercularis': 'Left-parsopercularis',
  'Left-parsorbitalis': 'Left-parsorbitalis',
  'Left-parstriangularis': 'Left-parstriangularis',
  'Left-pericalcarine': 'Left-pericalcarine',
  'Left-postcentral': 'Left-postcentral',
  'Left-posteriorcingulate': 'Left-posteriorcingulate',
  'Left-precentral': 'Left-precentral',
  'Left-precuneus': 'Left-precuneus',
  'Left-rostralanteriorcingulate': 'Left-rostralanteriorcingulate',
  'Left-rostralmiddlefrontal': 'Left-rostralmiddlefrontal',
  'Left-superiorfrontal': 'Left-superiorfrontal',
  'Left-superiorparietal': 'Left-superiorparietal',
  'Left-superiortemporal': 'Left-superiortemporal',
  'Left-supramarginal': 'Left-supramarginal',
  'Left-transversetemporal': 'Left-transversetemporal',
  'Left-unknown':-1 # this is actually the middle region inside the cortical surface. color it as gray
}




### For Custom ATLAS #####

# MAP from custom atlas to DK. Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
cortAreasIndexMapCustom = {
  'Right-bankssts':-1, # -1 means do not colour this region
  'Right-caudalanteriorcingulate':'Right-anterior cingulate',
  'Right-caudalmiddlefrontal':'Right-medial frontal',
  'Right-cuneus':'Right-cuneus',
  'Right-entorhinal':'Right-entorhinal',
  'Right-frontalpole':'Right-frontal pole',
  'Right-fusiform':'Right-fusiform',
  'Right-inferiorparietal':'Right-angular',
  'Right-inferiortemporal':'Right-inferior temporal',
  'Right-insula':'Right-anterior insula',
  'Right-isthmuscingulate':'Right-posterior cingulate',
  'Right-lateraloccipital':'Right-inferior occipital',
  'Right-lateralorbitofrontal':'Right-medial frontal',
  'Right-lingual':'Right-lingual',
  'Right-medialorbitofrontal':'Right-medial frontal',
  'Right-middletemporal':'Right-middle temporal',
  'Right-paracentral':'Right-precentral',
  'Right-parahippocampal':'Right-parahippocampal',
  'Right-parsopercularis':'Right-central operculum',
  'Right-parsorbitalis':'Right-anterior orbital',
  'Right-parstriangularis':'Right-angular',
  'Right-pericalcarine':'Right-calcarine',
  'Right-postcentral':'Right-postcentral',
  'Right-posteriorcingulate':'Right-posterior cingulate',
  'Right-precentral':'Right-precentral',
  'Right-precuneus':'Right-precuneus',
  'Right-rostralanteriorcingulate':'Right-anterior cingulate',
  'Right-rostralmiddlefrontal':'Right-middle frontal',
  'Right-superiorfrontal':'Right-superior frontal',
  'Right-superiorparietal':'Right-superior parietal',
  'Right-superiortemporal':'Right-superior temporal',
  'Right-supramarginal':'Right-supramarginal',
  'Right-temporalpole':'Right-temporal pole',
  'Right-transversetemporal':'Right-planum temporale',
  'Right-unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray

  'Left-bankssts':-1, # -1 means do not colour this region
  'Left-caudalanteriorcingulate':'Left-anterior cingulate',
  'Left-caudalmiddlefrontal':'Left-medial frontal',
  'Left-cuneus':'Left-cuneus',
  'Left-entorhinal':'Left-entorhinal',
  'Left-frontalpole':'Left-frontal pole',
  'Left-fusiform':'Left-fusiform',
  'Left-inferiorparietal':'Left-angular',
  'Left-inferiortemporal':'Left-inferior temporal',
  'Left-insula':'Left-anterior insula',
  'Left-isthmuscingulate':'Left-posterior cingulate',
  'Left-lateraloccipital':'Left-inferior occipital',
  'Left-lateralorbitofrontal':'Left-medial frontal',
  'Left-lingual':'Left-lingual',
  'Left-medialorbitofrontal':'Left-medial frontal',
  'Left-middletemporal':'Left-middle temporal',
  'Left-paracentral':'Left-precentral',
  'Left-parahippocampal':'Left-parahippocampal',
  'Left-parsopercularis':'Left-central operculum',
  'Left-parsorbitalis':'Left-anterior orbital',
  'Left-parstriangularis':'Left-angular',
  'Left-pericalcarine':'Left-calcarine',
  'Left-postcentral':'Left-postcentral',
  'Left-posteriorcingulate':'Left-posterior cingulate',
  'Left-precentral':'Left-precentral',
  'Left-precuneus':'Left-precuneus',
  'Left-rostralanteriorcingulate':'Left-anterior cingulate',
  'Left-rostralmiddlefrontal':'Left-middle frontal',
  'Left-superiorfrontal':'Left-superior frontal',
  'Left-superiorparietal':'Left-superior parietal',
  'Left-superiortemporal':'Left-superior temporal',
  'Left-supramarginal':'Left-supramarginal',
  'Left-temporalpole':'Left-temporal pole',
  'Left-transversetemporal':'Left-planum temporale',
  'Left-unknown':-1 # this is actually the middle region inside the cortical surface. color it as gray
}


# Subcortical areas
# this map is used by all atlases (DK, Destrieux, Tourville)
subcortAreasIndexMap = {
  'Left-Accumbens-area': 'Left-Accumbens-area', # -1 means do not colour this region
  'Left-Caudate': 'Left-Caudate',
  'Left-Cerebellum-White-Matter': 'Left-Cerebellum-White-Matter',
  'Left-Inf-Lat-Vent': 'Left-Inf-Lat-Vent',
  'Left-Pallidum': 'Left-Pallidum',
  'Left-Thalamus-Proper': 'Left-Thalamus-Proper',
  'Left-Amygdala': 'Left-Amygdala',
  'Left-Cerebellum-Cortex': 'Left-Cerebellum-Cortex',
  'Left-Hippocampus': 'Left-Hippocampus',
  'Left-Lateral-Ventricle': 'Left-Lateral-Ventricle',
  'Left-Putamen': 'Left-Putamen',
  'Left-VentralDC': 'Left-VentralDC', 

  'Right-Accumbens-area': 'Right-Accumbens-area', # -1 means do not colour this region
  'Right-Caudate': 'Right-Caudate',
  'Right-Cerebellum-White-Matter': 'Right-Cerebellum-White-Matter',
  'Right-Inf-Lat-Vent': 'Right-Inf-Lat-Vent',
  'Right-Pallidum': 'Right-Pallidum',
  'Right-Thalamus-Proper': 'Right-Thalamus-Proper',
  'Right-Amygdala': 'Right-Amygdala',
  'Right-Cerebellum-Cortex': 'Right-Cerebellum-Cortex',
  'Right-Hippocampus': 'Right-Hippocampus',
  'Right-Lateral-Ventricle': 'Right-Lateral-Ventricle',
  'Right-Putamen': 'Right-Putamen',
  'Right-VentralDC': 'Right-VentralDC'
  }


subcortAreasIndexMapCustom = {
  'Left-Accumbens-area':'Left-Accumbens-area', # -1 means do not colour this region
  'Left-Caudate':'Left-Caudate',
  'Left-Cerebellum-White-Matter':-1,
  'Left-Inf-Lat-Vent':-1,
  'Left-Pallidum':'Left-Pallidum',
  'Left-Thalamus-Proper':'Left-Thalamus',
  'Left-Amygdala':'Left-Amygdala',
  'Left-Cerebellum-Cortex':-1,
  'Left-Hippocampus':'Left-Hippocampus',
  'Left-Lateral-Ventricle':-1,
  'Left-Putamen':'Left-Putamen',
  'Left-VentralDC':'Left-VentralDC',

  'Right-Accumbens-area':'Right-Accumbens-area', # -1 means do not colour this region
  'Right-Caudate':'Right-Caudate',
  'Right-Cerebellum-White-Matter':-1,
  'Right-Inf-Lat-Vent':-1,
  'Right-Pallidum':'Right-Pallidum',
  'Right-Thalamus-Proper':'Right-Thalamus',
  'Right-Amygdala':'Right-Amygdala',
  'Right-Cerebellum-Cortex':-1,
  'Right-Hippocampus':'Right-Hippocampus',
  'Right-Lateral-Ventricle':-1,
  'Right-Putamen':'Right-Putamen',
  'Right-VentralDC':'Right-VentralDC'
}
