
INPUT_FILE = 'input/dorr_template.csv' # input template should match ATLAS below

OUTPUT_FOLDER = 'output/dorr_output'

# either 'DK', 'Destrieux', 'Tourville', 'Mice', 'Dorr', 'Dsurque' or 'Custom'
ATLAS = 'Dorr'

# either 'pial' (with gyri/sulci), 'inflated' (smooth) or 'white' (white-matter surface)
BRAIN_TYPE = 'pial'

# either cortical-outer, cortical-inner, subcortical 
# add -right-hemisphere or -left-hemisphere to end of image type to specify view
# image types "top" and "bottom" are available to show asymmetry
IMG_TYPE = 'top'

# what colours to use for showing brain pathology
# e.g. if the range of pathology is [0,3],
# then you need four colors (the first one is for pathology 0, i.e. no pathology)
# a pathology at 1.3 will interpolate between the second and third color

# NOTE: you can add more than 4 colours (as many as you want), in which case you should increase the range of the input biomarkers.
COLORS_RGB = [(1,1,1), (1,1,0), (1,0.4,0), (1,0,0)] # white -> yellow -> orange -> red
# COLORS_RGB = [(1,1,1), (1,0,0), (1,0,0), (1,0,0)] # white -> red -> red -> red

# output image resolution for X,Y in pixels
RESOLUTION = (1200, 900)

# default is white
BACKGROUND_COLOR = (1,1,1)

# to change camera viewing angle and other advanced settings, look into blendHelper.py:setCamera()
# for luminosity settings, look into blendHelper.py:setLamp()

if ATLAS == 'Mice' or ATLAS == 'Dorr' or ATLAS == 'Dsurque': 
    # we do not have white/inflated for mice yet
    BRAIN_TYPE = 'pial'



### Advanced settings, only change if you want to use custom atlas or if you'd like to not color at all some regions #####

# map the names of each 3D cortical structure to be coloured to the name of the structure you have in your atlas.
# only change the right-hand side values, as the left-hand side are used by blender.

# Common customisations:
# 1. to completely remove a region from being displayed, remove both the (key,value) pair.
# 2. to deactivate a region (always color it in default dark gray color), map its value to -1

# NOTE: Always make sure the RHS regions (dict values) below are present in your input .csv file.

### DK atlas ###

# Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
# disable any regions by setting its RHS to -1
cortAreasIndexMapDK = {
  'Right-bankssts':'Right-bankssts',
  'Right-caudalanteriorcingulate':'Right-caudalanteriorcingulate',
  'Right-caudalmiddlefrontal':'Right-caudalmiddlefrontal',
  'Right-cuneus':'Right-cuneus',
  'Right-entorhinal':'Right-entorhinal',
  'Right-frontalpole': 'Right-frontalpole',
  'Right-fusiform':'Right-fusiform',
  'Right-inferiorparietal':'Right-inferiorparietal',
  'Right-inferiortemporal':'Right-inferiortemporal',
  'Right-insula':'Right-insula',
  'Right-isthmuscingulate':'Right-isthmuscingulate',
  'Right-lateraloccipital':'Right-lateraloccipital',
  'Right-lateralorbitofrontal':'Right-lateralorbitofrontal',
  'Right-lingual':'Right-lingual',
  'Right-medialorbitofrontal':'Right-medialorbitofrontal',
  'Right-middletemporal':'Right-middletemporal',
  'Right-paracentral':'Right-paracentral',
  'Right-parahippocampal':'Right-parahippocampal',
  'Right-parsopercularis':'Right-parsopercularis',
  'Right-parsorbitalis':'Right-parsorbitalis',
  'Right-parstriangularis':'Right-parstriangularis',
  'Right-pericalcarine':'Right-pericalcarine',
  'Right-postcentral':'Right-postcentral',
  'Right-posteriorcingulate':'Right-posteriorcingulate',
  'Right-precentral':'Right-precentral',
  'Right-precuneus':'Right-precuneus',
  'Right-rostralanteriorcingulate':'Right-rostralanteriorcingulate',
  'Right-rostralmiddlefrontal':'Right-rostralmiddlefrontal',
  'Right-superiorfrontal':'Right-superiorfrontal',
  'Right-superiorparietal':'Right-superiorparietal',
  'Right-superiortemporal':'Right-superiortemporal',
  'Right-supramarginal':'Right-supramarginal',
  'Right-temporalpole':'Right-temporalpole',
  'Right-transversetemporal':'Right-transversetemporal',
  'Right-unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray
  
  'Left-bankssts':'Left-bankssts',
  'Left-caudalanteriorcingulate':'Left-caudalanteriorcingulate',
  'Left-caudalmiddlefrontal':'Left-caudalmiddlefrontal',
  'Left-cuneus':'Left-cuneus',
  'Left-entorhinal':'Left-entorhinal',
  'Left-frontalpole': 'Left-frontalpole',
  'Left-fusiform':'Left-fusiform',
  'Left-inferiorparietal':'Left-inferiorparietal',
  'Left-inferiortemporal':'Left-inferiortemporal',
  'Left-insula':'Left-insula',
  'Left-isthmuscingulate':'Left-isthmuscingulate',
  'Left-lateraloccipital':'Left-lateraloccipital',
  'Left-lateralorbitofrontal':'Left-lateralorbitofrontal',
  'Left-lingual':'Left-lingual',
  'Left-medialorbitofrontal':'Left-medialorbitofrontal',
  'Left-middletemporal':'Left-middletemporal',
  'Left-paracentral':'Left-paracentral',
  'Left-parahippocampal':'Left-parahippocampal',
  'Left-parsopercularis':'Left-parsopercularis',
  'Left-parsorbitalis':'Left-parsorbitalis',
  'Left-parstriangularis':'Left-parstriangularis',
  'Left-pericalcarine':'Left-pericalcarine',
  'Left-postcentral':'Left-postcentral',
  'Left-posteriorcingulate':'Left-posteriorcingulate',
  'Left-precentral':'Left-precentral',
  'Left-precuneus':'Left-precuneus',
  'Left-rostralanteriorcingulate':'Left-rostralanteriorcingulate',
  'Left-rostralmiddlefrontal':'Left-rostralmiddlefrontal',
  'Left-superiorfrontal':'Left-superiorfrontal',
  'Left-superiorparietal':'Left-superiorparietal',
  'Left-superiortemporal':'Left-superiortemporal',
  'Left-supramarginal':'Left-supramarginal',
  'Left-temporalpole':'Left-temporalpole',
  'Left-transversetemporal':'Left-transversetemporal',
  'Left-unknown':-1 # this is actually the middle region inside the cortical surface. color it as gray
}


### Destrieux atlas ###

# Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
cortAreasIndexMapDestrieux = {
    'Right-G_and_S_frontomargin': 'Right-G_and_S_frontomargin',
    'Right-G_and_S_occipital_inf': 'Right-G_and_S_occipital_inf',
    'Right-G_and_S_paracentral': 'Right-G_and_S_paracentral',
    'Right-G_and_S_subcentral': 'Right-G_and_S_subcentral',
    'Right-G_and_S_transv_frontopol': 'Right-G_and_S_transv_frontopol' ,
    'Right-G_and_S_cingul-Ant': 'Right-G_and_S_cingul-Ant',
    'Right-G_and_S_cingul-Mid-Ant': 'Right-G_and_S_cingul-Mid-Ant',
    'Right-G_and_S_cingul-Mid-Post': 'Right-G_and_S_cingul-Mid-Post',
    'Right-G_cingul-Post-dorsal': 'Right-G_cingul-Post-dorsal',
    'Right-G_cingul-Post-ventral': 'Right-G_cingul-Post-ventral',
    'Right-G_cuneus': 'Right-G_cuneus',
    'Right-G_front_inf-Opercular': 'Right-G_front_inf-Opercular',
    'Right-G_front_inf-Orbital': 'Right-G_front_inf-Orbital',
    'Right-G_front_inf-Triangul': 'Right-G_front_inf-Triangul' ,
    'Right-G_front_middle': 'Right-G_front_middle',
    'Right-G_front_sup': 'Right-G_front_sup',
    'Right-G_Ins_lg_and_S_cent_ins': 'Right-G_Ins_lg_and_S_cent_ins',
    'Right-G_insular_short': 'Right-G_insular_short',
    'Right-G_occipital_middle': 'Right-G_occipital_middle',
    'Right-G_occipital_sup': 'Right-G_occipital_sup',
    'Right-G_oc-temp_lat-fusifor': 'Right-G_oc-temp_lat-fusifor',
    'Right-G_oc-temp_med-Lingual': 'Right-G_oc-temp_med-Lingual' ,
    'Right-G_oc-temp_med-Parahip': 'Right-G_oc-temp_med-Parahip' ,
    'Right-G_orbital': 'Right-G_orbital',
    'Right-G_pariet_inf-Angular': 'Right-G_pariet_inf-Angular',
    'Right-G_pariet_inf-Supramar': 'Right-G_pariet_inf-Supramar',
    'Right-G_parietal_sup': 'Right-G_parietal_sup',
    'Right-G_postcentral': 'Right-G_postcentral',
    'Right-G_precentral': 'Right-G_precentral',
    'Right-G_precuneus': 'Right-G_precuneus',
    'Right-G_rectus': 'Right-G_rectus',
    'Right-G_subcallosal': 'Right-G_subcallosal',
    'Right-G_temp_sup-G_T_transv': 'Right-G_temp_sup-G_T_transv',
    'Right-G_temp_sup-Lateral': 'Right-G_temp_sup-Lateral',
    'Right-G_temp_sup-Plan_polar': 'Right-G_temp_sup-Plan_polar' ,
    'Right-G_temp_sup-Plan_tempo': 'Right-G_temp_sup-Plan_tempo' ,
    'Right-G_temporal_inf': 'Right-G_temporal_inf',
    'Right-G_temporal_middle': 'Right-G_temporal_middle',
    'Right-Lat_Fis-ant-Horizont': 'Right-Lat_Fis-ant-Horizont',
    'Right-Lat_Fis-ant-Vertical': 'Right-Lat_Fis-ant-Vertical',
    'Right-Lat_Fis-post': 'Right-Lat_Fis-post',
    'Right-Pole_occipital': 'Right-Pole_occipital',
    'Right-Pole_temporal': 'Right-Pole_temporal',
    'Right-S_calcarine': 'Right-S_calcarine',
    'Right-S_central': 'Right-S_central',
    'Right-S_cingul-Marginalis': 'Right-S_cingul-Marginalis',
    'Right-S_circular_insula_ant': 'Right-S_circular_insula_ant',
    'Right-S_circular_insula_inf': 'Right-S_circular_insula_inf',
    'Right-S_circular_insula_sup': 'Right-S_circular_insula_sup',
    'Right-S_collat_transv_ant': 'Right-S_collat_transv_ant',
    'Right-S_collat_transv_post': 'Right-S_collat_transv_post',
    'Right-S_front_inf': 'Right-S_front_inf',
    'Right-S_front_middle': 'Right-S_front_middle',
    'Right-S_front_sup': 'Right-S_front_sup',
    'Right-S_interm_prim-Jensen': 'Right-S_interm_prim-Jensen',
    'Right-S_intrapariet_and_P_trans': 'Right-S_intrapariet_and_P_trans',
    'Right-S_oc_middle_and_Lunatus': 'Right-S_oc_middle_and_Lunatus',
    'Right-S_oc_sup_and_transversal': 'Right-S_oc_sup_and_transversal',
    'Right-S_occipital_ant': 'Right-S_occipital_ant',
    'Right-S_oc-temp_lat': 'Right-S_oc-temp_lat',
    'Right-S_oc-temp_med_and_Lingual': 'Right-S_oc-temp_med_and_Lingual',
    'Right-S_orbital_lateral': 'Right-S_orbital_lateral',
    'Right-S_orbital_med-olfact': 'Right-S_orbital_med-olfact',
    'Right-S_orbital-H_Shaped': 'Right-S_orbital-H_Shaped',
    'Right-S_parieto_occipital': 'Right-S_parieto_occipital',
    'Right-S_pericallosal': 'Right-S_pericallosal',
    'Right-S_postcentral': 'Right-S_postcentral',
    'Right-S_precentral-inf-part': 'Right-S_precentral-inf-part',
    'Right-S_precentral-sup-part': 'Right-S_precentral-sup-part',
    'Right-S_suborbital': 'Right-S_suborbital',
    'Right-S_subparietal': 'Right-S_subparietal',
    'Right-S_temporal_inf': 'Right-S_temporal_inf',
    'Right-S_temporal_sup': 'Right-S_temporal_sup',
    'Right-S_temporal_transverse': 'Right-S_temporal_transverse',
    'Right-Unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray


    'Left-G_and_S_frontomargin': 'Left-G_and_S_frontomargin',
    'Left-G_and_S_occipital_inf': 'Left-G_and_S_occipital_inf',
    'Left-G_and_S_paracentral': 'Left-G_and_S_paracentral',
    'Left-G_and_S_subcentral': 'Left-G_and_S_subcentral',
    'Left-G_and_S_transv_frontopol': 'Left-G_and_S_transv_frontopol' ,
    'Left-G_and_S_cingul-Ant': 'Left-G_and_S_cingul-Ant',
    'Left-G_and_S_cingul-Mid-Ant': 'Left-G_and_S_cingul-Mid-Ant',
    'Left-G_and_S_cingul-Mid-Post': 'Left-G_and_S_cingul-Mid-Post',
    'Left-G_cingul-Post-dorsal': 'Left-G_cingul-Post-dorsal',
    'Left-G_cingul-Post-ventral': 'Left-G_cingul-Post-ventral',
    'Left-G_cuneus': 'Left-G_cuneus',
    'Left-G_front_inf-Opercular': 'Left-G_front_inf-Opercular',
    'Left-G_front_inf-Orbital': 'Left-G_front_inf-Orbital',
    'Left-G_front_inf-Triangul': 'Left-G_front_inf-Triangul' ,
    'Left-G_front_middle': 'Left-G_front_middle',
    'Left-G_front_sup': 'Left-G_front_sup',
    'Left-G_Ins_lg_and_S_cent_ins': 'Left-G_Ins_lg_and_S_cent_ins',
    'Left-G_insular_short': 'Left-G_insular_short',
    'Left-G_occipital_middle': 'Left-G_occipital_middle',
    'Left-G_occipital_sup': 'Left-G_occipital_sup',
    'Left-G_oc-temp_lat-fusifor': 'Left-G_oc-temp_lat-fusifor',
    'Left-G_oc-temp_med-Lingual': 'Left-G_oc-temp_med-Lingual' ,
    'Left-G_oc-temp_med-Parahip': 'Left-G_oc-temp_med-Parahip' ,
    'Left-G_orbital': 'Left-G_orbital',
    'Left-G_pariet_inf-Angular': 'Left-G_pariet_inf-Angular',
    'Left-G_pariet_inf-Supramar': 'Left-G_pariet_inf-Supramar',
    'Left-G_parietal_sup': 'Left-G_parietal_sup',
    'Left-G_postcentral': 'Left-G_postcentral',
    'Left-G_precentral': 'Left-G_precentral',
    'Left-G_precuneus': 'Left-G_precuneus',
    'Left-G_rectus': 'Left-G_rectus',
    'Left-G_subcallosal': 'Left-G_subcallosal',
    'Left-G_temp_sup-G_T_transv': 'Left-G_temp_sup-G_T_transv',
    'Left-G_temp_sup-Lateral': 'Left-G_temp_sup-Lateral',
    'Left-G_temp_sup-Plan_polar': 'Left-G_temp_sup-Plan_polar' ,
    'Left-G_temp_sup-Plan_tempo': 'Left-G_temp_sup-Plan_tempo' ,
    'Left-G_temporal_inf': 'Left-G_temporal_inf',
    'Left-G_temporal_middle': 'Left-G_temporal_middle',
    'Left-Lat_Fis-ant-Horizont': 'Left-Lat_Fis-ant-Horizont',
    'Left-Lat_Fis-ant-Vertical': 'Left-Lat_Fis-ant-Vertical',
    'Left-Lat_Fis-post': 'Left-Lat_Fis-post',
    'Left-Pole_occipital': 'Left-Pole_occipital',
    'Left-Pole_temporal': 'Left-Pole_temporal',
    'Left-S_calcarine': 'Left-S_calcarine',
    'Left-S_central': 'Left-S_central',
    'Left-S_cingul-Marginalis': 'Left-S_cingul-Marginalis',
    'Left-S_circular_insula_ant': 'Left-S_circular_insula_ant',
    'Left-S_circular_insula_inf': 'Left-S_circular_insula_inf',
    'Left-S_circular_insula_sup': 'Left-S_circular_insula_sup',
    'Left-S_collat_transv_ant': 'Left-S_collat_transv_ant',
    'Left-S_collat_transv_post': 'Left-S_collat_transv_post',
    'Left-S_front_inf': 'Left-S_front_inf',
    'Left-S_front_middle': 'Left-S_front_middle',
    'Left-S_front_sup': 'Left-S_front_sup',
    'Left-S_interm_prim-Jensen': 'Left-S_interm_prim-Jensen',
    'Left-S_intrapariet_and_P_trans': 'Left-S_intrapariet_and_P_trans',
    'Left-S_oc_middle_and_Lunatus': 'Left-S_oc_middle_and_Lunatus',
    'Left-S_oc_sup_and_transversal': 'Left-S_oc_sup_and_transversal',
    'Left-S_occipital_ant': 'Left-S_occipital_ant',
    'Left-S_oc-temp_lat': 'Left-S_oc-temp_lat',
    'Left-S_oc-temp_med_and_Lingual': 'Left-S_oc-temp_med_and_Lingual',
    'Left-S_orbital_lateral': 'Left-S_orbital_lateral',
    'Left-S_orbital_med-olfact': 'Left-S_orbital_med-olfact',
    'Left-S_orbital-H_Shaped': 'Left-S_orbital-H_Shaped',
    'Left-S_parieto_occipital': 'Left-S_parieto_occipital',
    'Left-S_pericallosal': 'Left-S_pericallosal',
    'Left-S_postcentral': 'Left-S_postcentral',
    'Left-S_precentral-inf-part': 'Left-S_precentral-inf-part',
    'Left-S_precentral-sup-part': 'Left-S_precentral-sup-part',
    'Left-S_suborbital': 'Left-S_suborbital',
    'Left-S_subparietal': 'Left-S_subparietal',
    'Left-S_temporal_inf': 'Left-S_temporal_inf',
    'Left-S_temporal_sup': 'Left-S_temporal_sup',
    'Left-S_temporal_transverse': 'Left-S_temporal_transverse',
    'Left-Unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray
}

### Mouse brain atlas ###

# Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
cortAreasIndexMapMice = {
  'Right-Anterior-cingulate': 'Right-Anterior-cingulate',
  'Right-Auditory': 'Right-Auditory',
  'Right-Cortical-subplate': 'Right-Cortical-subplate',
  'Right-Gustatory': 'Right-Gustatory',
  'Right-Infralimbic': 'Right-Infralimbic',
  'Right-Medulla': 'Right-Medulla',
  'Right-Olfactory': 'Right-Olfactory',
  'Right-Pons': 'Right-Pons',
  'Right-Prelimbic': 'Right-Prelimbic',
  'Right-Retrosplenial': 'Right-Retrosplenial',
  'Right-Somatomotor': 'Right-Somatomotor',
  'Right-Somatosensory': 'Right-Somatosensory',
  'Right-Striatum': 'Right-Striatum',
  'Right-Visceral': 'Right-Visceral',
  'Right-Visual': 'Right-Visual', 
  'Right-Agranular-insular-area': 'Right-Agranular-insular-area', 
  'Right-Posterior-parietal-association-areas': 'Right-Posterior-parietal-association-areas', 
  'Right-Temporal-association-areas': 'Right-Temporal-association-areas',
  'Right-Perirhinal': 'Right-Perirhinal',
  'Right-Ectorhinal': 'Right-Ectorhinal',

  'Left-Anterior-cingulate': 'Left-Anterior-cingulate',
  'Left-Auditory': 'Left-Auditory',
  'Left-Cortical-subplate': 'Left-Cortical-subplate',
  'Left-Gustatory': 'Left-Gustatory',
  'Left-Infralimbic': 'Left-Infralimbic',
  'Left-Medulla': 'Left-Medulla',
  'Left-Olfactory': 'Left-Olfactory',
  'Left-Pons': 'Left-Pons',
  'Left-Prelimbic': 'Left-Prelimbic',
  'Left-Retrosplenial': 'Left-Retrosplenial',
  'Left-Somatomotor': 'Left-Somatomotor',
  'Left-Somatosensory': 'Left-Somatosensory',
  'Left-Striatum': 'Left-Striatum',
  'Left-Visceral': 'Left-Visceral',
  'Left-Visual': 'Left-Visual', 
  'Left-Agranular-insular-area': 'Left-Agranular-insular-area', 
  'Left-Posterior-parietal-association-areas': 'Left-Posterior-parietal-association-areas', 
  'Left-Temporal-association-areas': 'Left-Temporal-association-areas',
  'Left-Perirhinal': 'Left-Perirhinal',
  'Left-Ectorhinal': 'Left-Ectorhinal',
}

# subcortical areas for mouse atlas
subcortMouseAreasIndexMap = {
  'Left-Cerebellum':'Left-Cerebellum', # -1 means do not colour this region
  'Left-Hypothalamus':'Left-Hypothalamus',
  'Left-Frontal-pole': 'Left-Frontal-pole', # Acronym for Frontal pole, cerebral cortex,
  'Left-Hippocampus': 'Left-Hippocampus',
  'Left-Midbrain':'Left-Midbrain',
  'Left-Pallidum': 'Left-Pallidum',
  'Left-Thalamus':'Left-Thalamus',

  'Right-Cerebellum':'Right-Cerebellum', # -1 means do not colour this region
  'Right-Hypothalamus':'Right-Hypothalamus',
  'Right-Frontal-pole': 'Right-Frontal-pole', # Acronym for Frontal pole, cerebral cortex,
  'Right-Hippocampus': 'Right-Hippocampus',
  'Right-Midbrain':'Right-Midbrain',
  'Right-Pallidum': 'Right-Pallidum',
  'Right-Thalamus':'Right-Thalamus'
}

# subcortical regions for the dorr atlas
subcortDorrAreasIndexMap = {
  'bilateral_cerebral_aqueduct.ply': 'bilateral_cerebral_aqueduct.ply',
  'bilateral_fourth_ventricle.ply': 'bilateral_fourth_ventricle.ply',
  'bilateral_interpedunclar_nucleus.ply': 'bilateral_interpedunclar_nucleus.ply',
  'bilateral_medulla.ply': 'bilateral_medulla.ply',
  'bilateral_midbrain.ply': 'bilateral_midbrain.ply',
  'bilateral_periaqueductal_grey.ply': 'bilateral_periaqueductal_grey.ply',
  'bilateral_pons.ply': 'bilateral_pons.ply',
  'bilateral_posterior_commissure.ply': 'bilateral_posterior_commissure.ply',
  'bilateral_third_ventricle.ply': 'bilateral_third_ventricle.ply',
  'bilateral_ventral_tegmental_decussation.ply': 'bilateral_ventral_tegmental_decussation.ply',
}


# subcortical regions for the dsurque atlas
subcortDsurqueAreasIndexMap = {
  'bilateral_cerebral_aqueduct.ply': 'bilateral_cerebral_aqueduct.ply',
  'bilateral_fourth_ventricle.ply': 'bilateral_fourth_ventricle.ply',
  'bilateral_interpedunclar_nucleus.ply': 'bilateral_interpedunclar_nucleus.ply',
  'bilateral_lobule_10_nodulus.ply': 'bilateral_lobule_10_nodulus.ply',
  'bilateral_lobule_10_white_matter.ply': 'bilateral_lobule_10_white_matter.ply',
  'bilateral_lobule_1_2_white_matter.ply': 'bilateral_lobule_1_2_white_matter.ply',
  'bilateral_lobule_3_central_lobule_dorsal.ply': 'bilateral_lobule_3_central_lobule_dorsal.ply',
  'bilateral_lobule_3_white_matter.ply': 'bilateral_lobule_3_white_matter.ply',
  'bilateral_lobule_6_declive.ply': 'bilateral_lobule_6_declive.ply',
  'bilateral_lobule_7_tuber_or_folium.ply': 'bilateral_lobule_7_tuber_or_folium.ply',
  'bilateral_lobule_8_pyramis.ply': 'bilateral_lobule_8_pyramis.ply',
  'bilateral_lobule_8_white_matter.ply': 'bilateral_lobule_8_white_matter.ply',
  'bilateral_lobule_9_uvula.ply': 'bilateral_lobule_9_uvula.ply',
  'bilateral_lobule_9_white_matter.ply': 'bilateral_lobule_9_white_matter.ply',
  'bilateral_lobules_1_2_lingula_and_central_lobule_ventral.ply': 'bilateral_lobules_1_2_lingula_and_central_lobule_ventral.ply',
  'bilateral_lobules_4_5_culmen_ventral_and_dorsal.ply': 'bilateral_lobules_4_5_culmen_ventral_and_dorsal.ply',
  'bilateral_lobules_4_5_white_matter.ply': 'bilateral_lobules_4_5_white_matter.ply',
  'bilateral_lobules_6_7_white_matter.ply': 'bilateral_lobules_6_7_white_matter.ply',
  'bilateral_medulla.ply': 'bilateral_medulla.ply',
  'bilateral_midbrain.ply': 'bilateral_midbrain.ply',
  'bilateral_periaqueductal_grey.ply': 'bilateral_periaqueductal_grey.ply',
  'bilateral_pons.ply': 'bilateral_pons.ply',
  'bilateral_posterior_commissure.ply': 'bilateral_posterior_commissure.ply',
  'bilateral_third_ventricle.ply': 'bilateral_third_ventricle.ply',
  'bilateral_trunk_of_arbor_vita.ply': 'bilateral_trunk_of_arbor_vita.ply',
  'bilateral_trunk_of_lobules_1_3_white_matter.ply': 'bilateral_trunk_of_lobules_1_3_white_matter.ply',
  'bilateral_trunk_of_lobules_6_8_white_matter.ply': 'bilateral_trunk_of_lobules_6_8_white_matter.ply',
  'bilateral_ventral_tegmental_decussation.ply': 'bilateral_ventral_tegmental_decussation.ply',
}

cortAreasIndexMapDsurque = {
  'left_accessory_olfactory_bulb_glomerular_external_plexiform_and_mitral_cell_layer.ply': 'left_accessory_olfactory_bulb_glomerular_external_plexiform_and_mitral_cell_layer.ply',
  'left_accessory_olfdactory_bulb_granule_cell_layer.ply': 'left_accessory_olfactory_bulb_granule_cell_layer.ply',
  'left_amygdala.ply': 'left_amygdala.ply',
  'left_amygdalopiriform_transition_area.ply': 'left_amygdalopiriform_transition_area.ply',
  'left_anterior_commissure_pars_anterior.ply': 'left_anterior_commissure_pars_anterior.ply',
  'left_anterior_commissure_pars_posterior.ply': 'left_anterior_commissure_pars_posterior.ply',
  'left_anterior_lobule_lobules_4_5.ply': 'left_anterior_lobule_lobules_4_5.ply',
  'left_anterior_lobule_white_matter.ply': 'left_anterior_lobule_white_matter.ply',
  'left_anterior_olfactory_nucleus.ply': 'left_anterior_olfactory_nucleus.ply',
  'left_basal_forebrain.ply': 'left_basal_forebrain.ply',
  'left_bed_nucleus_of_stria_terminalis.ply': 'left_bed_nucleus_of_stria_terminalis.ply',
  'left_ca10r.ply': 'left_ca10r.ply',
  'left_ca1py.ply': 'left_ca1py.ply',
  'left_ca1rad.ply': 'left_ca1rad.ply',
  'left_ca20r.ply': 'left_ca20r.ply',
  'left_ca2py.ply': 'left_ca2py.ply',
  'left_ca2rad.ply': 'left_ca2rad.ply',
  'left_ca30r.ply': 'left_ca30r.ply',
  'left_ca3py_inner.ply': 'left_ca3py_inner.ply',
  'left_ca3py_outer.ply': 'left_ca3py_outer.ply',
  'left_ca3rad.ply': 'left_ca3rad.ply',
  'left_caudomedial_entorhinal_cortex.ply': 'left_caudomedial_entorhinal_cortex.ply',
  'left_cerebellar_peduncle_inferior.ply': 'left_cerebellar_peduncle_inferior.ply',
  'left_cerebellar_peduncle_middle.ply': 'left_cerebellar_peduncle_middle.ply',
  'left_cerebellar_peduncle_superior.ply': 'left_cerebellar_peduncle_superior.ply',
  'left_cerebral_peduncle.ply': 'left_cerebral_peduncle.ply',
  'left_cingulate_cortex_area_24a.ply': 'left_cingulate_cortex_area_24a.ply',
  'left_cingulate_cortex_area_24a_2.ply': 'left_cingulate_cortex_area_24a_2.ply',
  'left_cingulate_cortex_area_24b.ply': 'left_cingulate_cortex_area_24b.ply',
  'left_cingulate_cortex_area_24b_2.ply': 'left_cingulate_cortex_area_24b_2.ply',
  'left_cingulate_cortex_area_25.ply': 'left_cingulate_cortex_area_25.ply',
  'left_cingulate_cortex_area_29a.ply': 'left_cingulate_cortex_area_29a.ply',
  'left_cingulate_cortex_area_29b.ply': 'left_cingulate_cortex_area_29b.ply',
  'left_cingulate_cortex_area_29c.ply': 'left_cingulate_cortex_area_29c.ply',
  'left_cingulate_cortex_area_30.ply': 'left_cingulate_cortex_area_30.ply',
  'left_cingulate_cortex_area_32.ply': 'left_cingulate_cortex_area_32.ply',
  'left_cingulum.ply': 'left_cingulum.ply',
  'left_claustrum.ply': 'left_claustrum.ply',
  'left_claustrum_dorsal_part.ply': 'left_claustrum_dorsal_part.ply',
  'left_claustrum_ventral_part.ply': 'left_claustrum_ventral_part.ply',
  'left_colliculus_inferior.ply': 'left_colliculus_inferior.ply',
  'left_colliculus_superior.ply': 'left_colliculus_superior.ply',
  'left_copula_pyramis_lobule_8.ply': 'left_copula_pyramis_lobule_8.ply',
  'left_copula_white_matter.ply': 'left_copula_white_matter.ply',
  'left_corpus_callosum.ply': 'left_corpus_callosum.ply',
  'left_cortex_amygdala_transition_zones.ply': 'left_cortex_amygdala_transition_zones.ply',
  'left_corticospinal_tract_pyramids.ply': 'left_corticospinal_tract_pyramids.ply',
  'left_crus_1_ansiform_lobule_lobule_6.ply': 'left_crus_1_ansiform_lobule_lobule_6.ply',
  'left_crus_1_white_matter.ply': 'left_crus_1_white_matter.ply',
  'left_crus_2_ansiform_lobule_lobule_7.ply': 'left_crus_2_ansiform_lobule_lobule_7.ply',
  'left_crus_2_white_matter.ply': 'left_crus_2_white_matter.ply',
  'left_cuneate_nucleus.ply': 'left_cuneate_nucleus.ply',
  'left_dentate_nucleus.ply': 'left_dentate_nucleus.ply',
  'left_dorsal_intermediate_entorhinal_cortex.ply': 'left_dorsal_intermediate_entorhinal_cortex.ply',
  'left_dorsal_nucleus_of_the_endopiriform.ply': 'left_dorsal_nucleus_of_the_endopiriform.ply',
  'left_dorsal_tenia_tecta.ply': 'left_dorsal_tenia_tecta.ply',
  'left_dorsolateral_entorhinal_cortex.ply': 'left_dorsolateral_entorhinal_cortex.ply',
  'left_dorsolateral_orbital_cortex.ply': 'left_dorsolateral_orbital_cortex.ply',
  'left_ectorhinal_cortex.ply': 'left_ectorhinal_cortex.ply',
  'left_facial_nerve_cranial_nerve_7.ply': 'left_facial_nerve_cranial_nerve_7.ply',
  'left_fasciculus_retroflexus.ply': 'left_fasciculus_retroflexus.ply',
  'left_fastigial_nucleus.ply': 'left_fastigial_nucleus.ply',
  'left_fimbria.ply': 'left_fimbria.ply',
  'left_flocculus_fl.ply': 'left_flocculus_fl.ply',
  'left_flocculus_white_matter.ply': 'left_flocculus_white_matter.ply',
  'left_fornix.ply': 'left_fornix.ply',
  'left_frontal_association_cortex.ply': 'left_frontal_association_cortex.ply',
  'left_frontal_cortex_area_3.ply': 'left_frontal_cortex_area_3.ply',
  'left_fundus_of_striatum.ply': 'left_fundus_of_striatum.ply',
  'left_globus_pallidus.ply': 'left_globus_pallidus.ply',
  'left_gr_dg.ply': 'left_gr_dg.ply',
  'left_habenular_commissure.ply': 'left_habenular_commissure.ply',
  'left_hypothalamus.ply': 'left_hypothalamus.ply',
  'left_inferior_olivary_complex.ply': 'left_inferior_olivary_complex.ply',
  'left_insular_region_not_subdivided.ply': 'left_insular_region_not_subdivided.ply',
  'left_intermediate_nucleus_of_the_endopiriform_claustrum.ply': 'left_intermediate_nucleus_of_the_endopiriform_claustrum.ply',
  'left_internal_capsule.ply': 'left_internal_capsule.ply',
  'left_l_mol.ply': 'left_l_mol.ply',
  'left_lateral_olfactory_tract.ply': 'left_lateral_olfactory_tract.ply',
  'left_lateral_orbital_cortex.ply': 'left_lateral_orbital_cortex.ply',
  'left_lateral_parietal_association_cortex.ply': 'left_lateral_parietal_association_cortex.ply',
  'left_lateral_septum.ply': 'left_lateral_septum.ply',
  'left_lateral_ventricle.ply': 'left_lateral_ventricle.ply',
  'left_mammillary_bodies.ply': 'left_mammillary_bodies.ply',
  'left_mammilothalamic_tract.ply': 'left_mammilothalamic_tract.ply',
  'left_medial_amygdala.ply': 'left_medial_amygdala.ply',
  'left_medial_entorhinal_cortex.ply': 'left_medial_entorhinal_cortex.ply',
  'left_medial_lemniscus_medial_longitudinal_fasciculus.ply': 'left_medial_lemniscus_medial_longitudinal_fasciculus.ply',
  'left_medial_orbital_cortex.ply': 'left_medial_orbital_cortex.ply',
  'left_medial_parietal_association_cortex.ply': 'left_medial_parietal_association_cortex.ply',
  'left_medial_preoptic_nucleus.ply': 'left_medial_preoptic_nucleus.ply',
  'left_medial_septum.ply': 'left_medial_septum.ply',
  'left_mo_dg_right.ply': 'left_mo_dg_right.ply',
  'left_nucleus_accumbens.ply': 'left_nucleus_accumbens.ply',
  'left_nucleus_interpositus.ply': 'left_nucleus_interpositus.ply',
  'left_olfactory_bulb_external_plexiform_layer.ply': 'left_olfactory_bulb_external_plexiform_layer.ply',
  'left_olfactory_bulb_glomerular_layer.ply': 'left_olfactory_bulb_glomerular_layer.ply',
  'left_olfactory_bulb_granule_cell_layer.ply': 'left_olfactory_bulb_granule_cell_layer.ply',
  'left_olfactory_bulb_internal_plexiform_layer.ply': 'left_olfactory_bulb_internal_plexiform_layer.ply',
  'left_olfactory_bulb_mitral_cell_layer.ply': 'left_olfactory_bulb_mitral_cell_layer.ply',
  'left_olfactory_peduncle.ply': 'left_olfactory_peduncle.ply',
  'left_olfactory_tubercle.ply': 'left_olfactory_tubercle.ply',
  'left_optic_tract.ply': 'left_optic_tract.ply',
  'left_paraflocculus_pfl.ply': 'left_paraflocculus_pfl.ply',
  'left_paraflocculus_white_matter.ply': 'left_paraflocculus_white_matter.ply',
  'left_paramedian_lobule.ply': 'left_paramedian_lobule.ply',
  'left_paramedian_lobule_lobule_7.ply': 'left_paramedian_lobule_lobule_7.ply',
  'left_parietal_cortex_posterior_area_rostral_part.ply': 'left_parietal_cortex_posterior_area_rostral_part.ply',
  'left_perirhinal_cortex.ply': 'left_perirhinal_cortex.ply',
  'left_piriform_cortex.ply': 'left_piriform_cortex.ply',
  'left_po_dg.ply': 'left_po_dg.ply',
  'left_pontine_nucleus.ply': 'left_pontine_nucleus.ply',
  'left_posterolateral_cortical_amygdaloid_area.ply': 'left_posterolateral_cortical_amygdaloid_area.ply',
  'left_posteromedial_cortical_amygdaloid_area.ply': 'left_posteromedial_cortical_amygdaloid_area.ply',
  'left_pre_para_subiculum.ply': 'left_pre_para_subiculum.ply',
  'left_primary_auditory_cortex.ply': 'left_primary_auditory_cortex.ply',
  'left_primary_motor_cortex.ply': 'left_primary_motor_cortex.ply',
  'left_primary_somatosensory_cortex.ply': 'left_primary_somatosensory_cortex.ply',
  'left_primary_somatosensory_cortex_barrel_field.ply': 'left_primary_somatosensory_cortex_barrel_field.ply',
  'left_primary_somatosensory_cortex_dysgranular_zone.ply': 'left_primary_somatosensory_cortex_dysgranular_zone.ply',
  'left_primary_somatosensory_cortex_forelimb_region.ply': 'left_primary_somatosensory_cortex_forelimb_region.ply',
  'left_primary_somatosensory_cortex_hindlimb_region.ply': 'left_primary_somatosensory_cortex_hindlimb_region.ply',
  'left_primary_somatosensory_cortex_jaw_region.ply': 'left_primary_somatosensory_cortex_jaw_region.ply',
  'left_primary_somatosensory_cortex_shoulder_region.ply': 'left_primary_somatosensory_cortex_shoulder_region.ply',
  'left_primary_somatosensory_cortex_trunk_region.ply': 'left_primary_somatosensory_cortex_trunk_region.ply',
  'left_primary_somatosensory_cortex_upper_lip_region.ply': 'left_primary_somatosensory_cortex_upper_lip_region.ply',
  'left_primary_visual_cortex.ply': 'left_primary_visual_cortex.ply',
  'left_primary_visual_cortex_binocular_area.ply': 'left_primary_visual_cortex_binocular_area.ply',
  'left_primary_visual_cortex_monocular_area.ply': 'left_primary_visual_cortex_monocular_area.ply',
  'left_rostral_amygdalopiriform_area.ply': 'left_rostral_amygdalopiriform_area.ply',
  'left_s_lu.ply': 'left_s_lu.ply',
  'left_secondary_auditory_cortex_dorsal_area.ply': 'left_secondary_auditory_cortex_dorsal_area.ply',
  'left_secondary_auditory_cortex_ventral_area.ply': 'left_secondary_auditory_cortex_ventral_area.ply',
  'left_secondary_motor_cortex.ply': 'left_secondary_motor_cortex.ply',
  'left_secondary_somatosensory_cortex.ply': 'left_secondary_somatosensory_cortex.ply',
  'left_secondary_visual_cortex_lateral_area.ply': 'left_secondary_visual_cortex_lateral_area.ply',
  'left_secondary_visual_cortex_mediolateral_area.ply': 'left_secondary_visual_cortex_mediolateral_area.ply',
  'left_secondary_visual_cortex_mediomedial_area.ply': 'left_secondary_visual_cortex_mediomedial_area.ply',
  'left_simple_lobule_lobule_6.ply': 'left_simple_lobule_lobule_6.ply',
  'left_simple_lobule_white_matter.ply': 'left_simple_lobule_white_matter.ply',
  'left_stria_medullaris.ply': 'left_stria_medullaris.ply',
  'left_stria_terminalis.ply': 'left_stria_terminalis.ply',
  'left_striatum.ply': 'left_striatum.ply',
  'left_subependymale_zone_rhinocele.ply': 'left_subependymale_zone_rhinocele.ply',
  'left_subiculum.ply': 'left_subiculum.ply',
  'left_superior_olivary_complex.ply': 'left_superior_olivary_complex.ply',
  'left_temporal_association_area.ply': 'left_temporal_association_area.ply',
  'left_thalamus.ply': 'left_thalamus.ply',
  'left_trunk_of_crus_2_and_paramedian_white_matter.ply': 'left_trunk_of_crus_2_and_paramedian_white_matter.ply',
  'left_trunk_of_simple_and_crus_1_white_matter.ply': 'left_trunk_of_simple_and_crus_1_white_matter.ply',
  'left_ventral_intermediate_entorhinal_cortex.ply': 'left_ventral_intermediate_entorhinal_cortex.ply',
  'left_ventral_nucleus_of_the_endopiriform_claustrum.ply': 'left_ventral_nucleus_of_the_endopiriform_claustrum.ply',
  'left_ventral_orbital_cortex.ply': 'left_ventral_orbital_cortex.ply',
  'left_ventral_tenia_tecta.ply': 'left_ventral_tenia_tecta.ply',

  'right_accessory_olfactory_bulb_glomerular_external_plexiform_and_mitral_cell_layer.ply': 'right_accessory_olfactory_bulb_glomerular_external_plexiform_and_mitral_cell_layer.ply',
  'right_accessory_olfactory_bulb_granule_cell_layer.ply': 'right_accessory_olfactory_bulb_granule_cell_layer.ply',
  'right_amygdala.ply': 'right_amygdala.ply',
  'right_amygdalopiriform_transition_area.ply': 'right_amygdalopiriform_transition_area.ply',
  'right_anterior_commissure_pars_anterior.ply': 'right_anterior_commissure_pars_anterior.ply',
  'right_anterior_commissure_pars_posterior.ply': 'right_anterior_commissure_pars_posterior.ply',
  'right_anterior_lobule_lobules_4_5.ply': 'right_anterior_lobule_lobules_4_5.ply',
  'right_anterior_lobule_white_matter.ply': 'right_anterior_lobule_white_matter.ply',
  'right_anterior_olfactory_nucleus.ply': 'right_anterior_olfactory_nucleus.ply',
  'right_basal_forebrain.ply': 'right_basal_forebrain.ply',
  'right_bed_nucleus_of_stria_terminalis.ply': 'right_bed_nucleus_of_stria_terminalis.ply',
  'right_ca10r.ply': 'right_ca10r.ply',
  'right_ca1py.ply': 'right_ca1py.ply',
  'right_ca1rad.ply': 'right_ca1rad.ply',
  'right_ca20r.ply': 'right_ca20r.ply',
  'right_ca2py.ply': 'right_ca2py.ply',
  'right_ca2rad.ply': 'right_ca2rad.ply',
  'right_ca30r.ply': 'right_ca30r.ply',
  'right_ca3py_inner.ply': 'right_ca3py_inner.ply',
  'right_ca3py_outer.ply': 'right_ca3py_outer.ply',
  'right_ca3rad.ply': 'right_ca3rad.ply',
  'right_caudomedial_entorhinal_cortex.ply': 'right_caudomedial_entorhinal_cortex.ply',
  'right_cerebellar_peduncle_inferior.ply': 'right_cerebellar_peduncle_inferior.ply',
  'right_cerebellar_peduncle_middle.ply': 'right_cerebellar_peduncle_middle.ply',
  'right_cerebellar_peduncle_superior.ply': 'right_cerebellar_peduncle_superior.ply',
  'right_cerebral_peduncle.ply': 'right_cerebral_peduncle.ply',
  'right_cingulate_cortex_area_24a.ply': 'right_cingulate_cortex_area_24a.ply',
  'right_cingulate_cortex_area_24a_2.ply': 'right_cingulate_cortex_area_24a_2.ply',
  'right_cingulate_cortex_area_24b.ply': 'right_cingulate_cortex_area_24b.ply',
  'right_cingulate_cortex_area_24b_2.ply': 'right_cingulate_cortex_area_24b_2.ply',
  'right_cingulate_cortex_area_25.ply': 'right_cingulate_cortex_area_25.ply',
  'right_cingulate_cortex_area_29a.ply': 'right_cingulate_cortex_area_29a.ply',
  'right_cingulate_cortex_area_29b.ply': 'right_cingulate_cortex_area_29b.ply',
  'right_cingulate_cortex_area_29c.ply': 'right_cingulate_cortex_area_29c.ply',
  'right_cingulate_cortex_area_30.ply': 'right_cingulate_cortex_area_30.ply',
  'right_cingulate_cortex_area_32.ply': 'right_cingulate_cortex_area_32.ply',
  'right_cingulum.ply': 'right_cingulum.ply',
  'right_claustrum.ply': 'right_claustrum.ply',
  'right_claustrum_dorsal_part.ply': 'right_claustrum_dorsal_part.ply',
  'right_claustrum_ventral_part.ply': 'right_claustrum_ventral_part.ply',
  'right_colliculus_inferior.ply': 'right_colliculus_inferior.ply',
  'right_colliculus_superior.ply': 'right_colliculus_superior.ply',
  'right_copula_pyramis_lobule_8.ply': 'right_copula_pyramis_lobule_8.ply',
  'right_copula_white_matter.ply': 'right_copula_white_matter.ply',
  'right_corpus_callosum.ply': 'right_corpus_callosum.ply',
  'right_cortex_amygdala_transition_zones.ply': 'right_cortex_amygdala_transition_zones.ply',
  'right_corticospinal_tract_pyramids.ply': 'right_corticospinal_tract_pyramids.ply',
  'right_crus_1_ansiform_lobule_lobule_6.ply': 'right_crus_1_ansiform_lobule_lobule_6.ply',
  'right_crus_1_white_matter.ply': 'right_crus_1_white_matter.ply',
  'right_crus_2_ansiform_lobule_lobule_7.ply': 'right_crus_2_ansiform_lobule_lobule_7.ply',
  'right_crus_2_white_matter.ply': 'right_crus_2_white_matter.ply',
  'right_cuneate_nucleus.ply': 'right_cuneate_nucleus.ply',
  'right_dentate_nucleus.ply': 'right_dentate_nucleus.ply',
  'right_dorsal_intermediate_entorhinal_cortex.ply': 'right_dorsal_intermediate_entorhinal_cortex.ply',
  'right_dorsal_nucleus_of_the_endopiriform.ply': 'right_dorsal_nucleus_of_the_endopiriform.ply',
  'right_dorsal_tenia_tecta.ply': 'right_dorsal_tenia_tecta.ply',
  'right_dorsolateral_entorhinal_cortex.ply': 'right_dorsolateral_entorhinal_cortex.ply',
  'right_dorsolateral_orbital_cortex.ply': 'right_dorsolateral_orbital_cortex.ply',
  'right_ectorhinal_cortex.ply': 'right_ectorhinal_cortex.ply',
  'right_facial_nerve_cranial_nerve_7.ply': 'right_facial_nerve_cranial_nerve_7.ply',
  'right_fasciculus_retroflexus.ply': 'right_fasciculus_retroflexus.ply',
  'right_fastigial_nucleus.ply': 'right_fastigial_nucleus.ply',
  'right_fimbria.ply': 'right_fimbria.ply',
  'right_flocculus_fl.ply': 'right_flocculus_fl.ply',
  'right_flocculus_white_matter.ply': 'right_flocculus_white_matter.ply',
  'right_fornix.ply': 'right_fornix.ply',
  'right_frontal_association_cortex.ply': 'right_frontal_association_cortex.ply',
  'right_frontal_cortex_area_3.ply': 'right_frontal_cortex_area_3.ply',
  'right_fundus_of_striatum.ply': 'right_fundus_of_striatum.ply',
  'right_globus_pallidus.ply': 'right_globus_pallidus.ply',
  'right_gr_dg.ply': 'right_gr_dg.ply',
  'right_habenular_commissure.ply': 'right_habenular_commissure.ply',
  'right_hypothalamus.ply': 'right_hypothalamus.ply',
  'right_inferior_olivary_complex.ply': 'right_inferior_olivary_complex.ply',
  'right_insular_region_not_subdivided.ply': 'right_insular_region_not_subdivided.ply',
  'right_intermediate_nucleus_of_the_endopiriform_claustrum.ply': 'right_intermediate_nucleus_of_the_endopiriform_claustrum.ply',
  'right_internal_capsule.ply': 'right_internal_capsule.ply',
  'right_l_mol.ply': 'right_l_mol.ply',
  'right_lateral_olfactory_tract.ply': 'right_lateral_olfactory_tract.ply',
  'right_lateral_orbital_cortex.ply': 'right_lateral_orbital_cortex.ply',
  'right_lateral_parietal_association_cortex.ply': 'right_lateral_parietal_association_cortex.ply',
  'right_lateral_septum.ply': 'right_lateral_septum.ply',
  'right_lateral_ventricle.ply': 'right_lateral_ventricle.ply',
  'right_mammillary_bodies.ply': 'right_mammillary_bodies.ply',
  'right_mammilothalamic_tract.ply': 'right_mammilothalamic_tract.ply',
  'right_medial_amygdala.ply': 'right_medial_amygdala.ply',
  'right_medial_entorhinal_cortex.ply': 'right_medial_entorhinal_cortex.ply',
  'right_medial_lemniscus_medial_longitudinal_fasciculus.ply': 'right_medial_lemniscus_medial_longitudinal_fasciculus.ply',
  'right_medial_orbital_cortex.ply': 'right_medial_orbital_cortex.ply',
  'right_medial_parietal_association_cortex.ply': 'right_medial_parietal_association_cortex.ply',
  'right_medial_preoptic_nucleus.ply': 'right_medial_preoptic_nucleus.ply',
  'right_medial_septum.ply': 'right_medial_septum.ply',
  'right_mo_dg_right.ply': 'right_mo_dg_right.ply',
  'right_nucleus_accumbens.ply': 'right_nucleus_accumbens.ply',
  'right_nucleus_interpositus.ply': 'right_nucleus_interpositus.ply',
  'right_olfactory_bulb_external_plexiform_layer.ply': 'right_olfactory_bulb_external_plexiform_layer.ply',
  'right_olfactory_bulb_glomerular_layer.ply': 'right_olfactory_bulb_glomerular_layer.ply',
  'right_olfactory_bulb_granule_cell_layer.ply': 'right_olfactory_bulb_granule_cell_layer.ply',
  'right_olfactory_bulb_internal_plexiform_layer.ply': 'right_olfactory_bulb_internal_plexiform_layer.ply',
  'right_olfactory_bulb_mitral_cell_layer.ply': 'right_olfactory_bulb_mitral_cell_layer.ply',
  'right_olfactory_peduncle.ply': 'right_olfactory_peduncle.ply',
  'right_olfactory_tubercle.ply': 'right_olfactory_tubercle.ply',
  'right_optic_tract.ply': 'right_optic_tract.ply',
  'right_paraflocculus_pfl.ply': 'right_paraflocculus_pfl.ply',
  'right_paraflocculus_white_matter.ply': 'right_paraflocculus_white_matter.ply',
  'right_paramedian_lobule.ply': 'right_paramedian_lobule.ply',
  'right_paramedian_lobule_lobule_7.ply': 'right_paramedian_lobule_lobule_7.ply',
  'right_parietal_cortex_posterior_area_rostral_part.ply': 'right_parietal_cortex_posterior_area_rostral_part.ply',
  'right_perirhinal_cortex.ply': 'right_perirhinal_cortex.ply',
  'right_piriform_cortex.ply': 'right_piriform_cortex.ply',
  'right_po_dg.ply': 'right_po_dg.ply',
  'right_pontine_nucleus.ply': 'right_pontine_nucleus.ply',
  'right_posterolateral_cortical_amygdaloid_area.ply': 'right_posterolateral_cortical_amygdaloid_area.ply',
  'right_posteromedial_cortical_amygdaloid_area.ply': 'right_posteromedial_cortical_amygdaloid_area.ply',
  'right_pre_para_subiculum.ply': 'right_pre_para_subiculum.ply',
  'right_primary_auditory_cortex.ply': 'right_primary_auditory_cortex.ply',
  'right_primary_motor_cortex.ply': 'right_primary_motor_cortex.ply',
  'right_primary_somatosensory_cortex.ply': 'right_primary_somatosensory_cortex.ply',
  'right_primary_somatosensory_cortex_barrel_field.ply': 'right_primary_somatosensory_cortex_barrel_field.ply',
  'right_primary_somatosensory_cortex_dysgranular_zone.ply': 'right_primary_somatosensory_cortex_dysgranular_zone.ply',
  'right_primary_somatosensory_cortex_forelimb_region.ply': 'right_primary_somatosensory_cortex_forelimb_region.ply',
  'right_primary_somatosensory_cortex_hindlimb_region.ply': 'right_primary_somatosensory_cortex_hindlimb_region.ply',
  'right_primary_somatosensory_cortex_jaw_region.ply': 'right_primary_somatosensory_cortex_jaw_region.ply',
  'right_primary_somatosensory_cortex_shoulder_region.ply': 'right_primary_somatosensory_cortex_shoulder_region.ply',
  'right_primary_somatosensory_cortex_trunk_region.ply': 'right_primary_somatosensory_cortex_trunk_region.ply',
  'right_primary_somatosensory_cortex_upper_lip_region.ply': 'right_primary_somatosensory_cortex_upper_lip_region.ply',
  'right_primary_visual_cortex.ply': 'right_primary_visual_cortex.ply',
  'right_primary_visual_cortex_binocular_area.ply': 'right_primary_visual_cortex_binocular_area.ply',
  'right_primary_visual_cortex_monocular_area.ply': 'right_primary_visual_cortex_monocular_area.ply',
  'right_rostral_amygdalopiriform_area.ply': 'right_rostral_amygdalopiriform_area.ply',
  'right_s_lu.ply': 'right_s_lu.ply',
  'right_secondary_auditory_cortex_dorsal_area.ply': 'right_secondary_auditory_cortex_dorsal_area.ply',
  'right_secondary_auditory_cortex_ventral_area.ply': 'right_secondary_auditory_cortex_ventral_area.ply',
  'right_secondary_motor_cortex.ply': 'right_secondary_motor_cortex.ply',
  'right_secondary_somatosensory_cortex.ply': 'right_secondary_somatosensory_cortex.ply',
  'right_secondary_visual_cortex_lateral_area.ply': 'right_secondary_visual_cortex_lateral_area.ply',
  'right_secondary_visual_cortex_mediolateral_area.ply': 'right_secondary_visual_cortex_mediolateral_area.ply',
  'right_secondary_visual_cortex_mediomedial_area.ply': 'right_secondary_visual_cortex_mediomedial_area.ply',
  'right_simple_lobule_lobule_6.ply': 'right_simple_lobule_lobule_6.ply',
  'right_simple_lobule_white_matter.ply': 'right_simple_lobule_white_matter.ply',
  'right_stria_medullaris.ply': 'right_stria_medullaris.ply',
  'right_stria_terminalis.ply': 'right_stria_terminalis.ply',
  'right_striatum.ply': 'right_striatum.ply',
  'right_subependymale_zone_rhinocele.ply': 'right_subependymale_zone_rhinocele.ply',
  'right_subiculum.ply': 'right_subiculum.ply',
  'right_superior_olivary_complex.ply': 'right_superior_olivary_complex.ply',
  'right_temporal_association_area.ply': 'right_temporal_association_area.ply',
  'right_thalamus.ply': 'right_thalamus.ply',
  'right_trunk_of_crus_2_and_paramedian_white_matter.ply': 'right_trunk_of_crus_2_and_paramedian_white_matter.ply',
  'right_trunk_of_simple_and_crus_1_white_matter.ply': 'right_trunk_of_simple_and_crus_1_white_matter.ply',
  'right_ventral_intermediate_entorhinal_cortex.ply': 'right_ventral_intermediate_entorhinal_cortex.ply',
  'right_ventral_nucleus_of_the_endopiriform_claustrum.ply': 'right_ventral_nucleus_of_the_endopiriform_claustrum.ply',
  'right_ventral_orbital_cortex.ply': 'right_ventral_orbital_cortex.ply',
  'right_ventral_tenia_tecta.ply': 'right_ventral_tenia_tecta.ply',
}

# Dorr areas for mouse atlas
cortAreasIndexMapDorr = {
  'left_amygdala.ply': 'left_amygdala.ply',
  'left_anterior_commissure_pars_anterior.ply': 'left_anterior_commissure_pars_anterior.ply',
  'left_anterior_commissure_pars_posterior.ply': 'left_anterior_commissure_pars_posterior.ply',
  'left_arbor_vita_of_cerebellum.ply': 'left_arbor_vita_of_cerebellum.ply',
  'left_basal_forebrain.ply': 'left_basal_forebrain.ply',
  'left_bed_nucleus_of_stria_terminalis.ply': 'left_bed_nucleus_of_stria_terminalis.ply',
  'left_cerebellar_cortex.ply': 'left_cerebellar_cortex.ply',
  'left_cerebellar_peduncle_inferior.ply': 'left_cerebellar_peduncle_inferior.ply',
  'left_cerebellar_peduncle_middle.ply': 'left_cerebellar_peduncle_middle.ply',
  'left_cerebellar_peduncle_superior.ply': 'left_cerebellar_peduncle_superior.ply',
  'left_cerebral_cortex_entorhinal_cortex.ply': 'left_cerebral_cortex_entorhinal_cortex.ply',
  'left_cerebral_cortex_frontal_lobe.ply': 'left_cerebral_cortex_frontal_lobe.ply',
  'left_cerebral_cortex_occipital_lobe.ply': 'left_cerebral_cortex_occipital_lobe.ply',
  'left_cerebral_cortex_parieto_temporal_lobe.ply': 'left_cerebral_cortex_parieto_temporal_lobe.ply',
  'left_cerebral_peduncle.ply': 'left_cerebral_peduncle.ply',
  'left_colliculus_inferior.ply': 'left_colliculus_inferior.ply',
  'left_colliculus_superior.ply': 'left_colliculus_superior.ply',
  'left_corpus_callosum.ply': 'left_corpus_callosum.ply',
  'left_corticospinal_tract_pyramids.ply': 'left_corticospinal_tract_pyramids.ply',
  'left_cuneate_nucleus.ply': 'left_cuneate_nucleus.ply',
  'left_dentate_gyrus_of_hippocampus.ply': 'left_dentate_gyrus_of_hippocampus.ply',
  'left_facial_nerve_cranial_nerve_7.ply': 'left_facial_nerve_cranial_nerve_7.ply',
  'left_fasciculus_retroflexus.ply': 'left_fasciculus_retroflexus.ply',
  'left_fimbria.ply': 'left_fimbria.ply',
  'left_fornix.ply': 'left_fornix.ply',
  'left_fundus_of_striatum.ply': 'left_fundus_of_striatum.ply',
  'left_globus_pallidus.ply': 'left_globus_pallidus.ply',
  'left_habenular_commissure.ply': 'left_habenular_commissure.ply',
  'left_hippocampus.ply': 'left_hippocampus.ply',
  'left_hypothalamus.ply': 'left_hypothalamus.ply',
  'left_inferior_olivary_complex.ply': 'left_inferior_olivary_complex.ply',
  'left_internal_capsule.ply': 'left_internal_capsule.ply',
  'left_lateral_olfactory_tract.ply': 'left_lateral_olfactory_tract.ply',
  'left_lateral_septum.ply': 'left_lateral_septum.ply',
  'left_lateral_ventricle.ply': 'left_lateral_ventricle.ply',
  'left_mammillary_bodies.ply': 'left_mammillary_bodies.ply',
  'left_mammilothalamic_tract.ply': 'left_mammilothalamic_tract.ply',
  'left_medial_lemniscus_medial_longitudinal_fasciculus.ply': 'left_medial_lemniscus_medial_longitudinal_fasciculus.ply',
  'left_medial_septum.ply': 'left_medial_septum.ply',
  'left_nucleus_accumbens.ply': 'left_nucleus_accumbens.ply',
  'left_olfactory_bulbs.ply': 'left_olfactory_bulbs.ply',
  'left_olfactory_tubercle.ply': 'left_olfactory_tubercle.ply',
  'left_optic_tract.ply': 'left_optic_tract.ply',
  'left_pontine_nucleus.ply': 'left_pontine_nucleus.ply',
  'left_pre_para_subiculum.ply': 'left_pre_para_subiculum.ply',
  'left_stratum_granulosum_of_hippocampus.ply': 'left_stratum_granulosum_of_hippocampus.ply',
  'left_stria_medullaris.ply': 'left_stria_medullaris.ply',
  'left_stria_terminalis.ply': 'left_stria_terminalis.ply',
  'left_striatum.ply': 'left_striatum.ply',
  'left_subependymale_zone_rhinocele.ply': 'left_subependymale_zone_rhinocele.ply',
  'left_superior_olivary_complex.ply': 'left_superior_olivary_complex.ply',
  'left_thalamus.ply': 'left_thalamus.ply',

  'right_amygdala.ply': 'right_amygdala.ply',
  'right_anterior_commissure_pars_anterior.ply': 'right_anterior_commissure_pars_anterior.ply',
  'right_anterior_commissure_pars_posterior.ply': 'right_anterior_commissure_pars_posterior.ply',
  'right_arbor_vita_of_cerebellum.ply': 'right_arbor_vita_of_cerebellum.ply',
  'right_basal_forebrain.ply': 'right_basal_forebrain.ply',
  'right_bed_nucleus_of_stria_terminalis.ply': 'right_bed_nucleus_of_stria_terminalis.ply',
  'right_cerebellar_cortex.ply': 'right_cerebellar_cortex.ply',
  'right_cerebellar_peduncle_inferior.ply': 'right_cerebellar_peduncle_inferior.ply',
  'right_cerebellar_peduncle_middle.ply': 'right_cerebellar_peduncle_middle.ply',
  'right_cerebellar_peduncle_superior.ply': 'right_cerebellar_peduncle_superior.ply',
  'right_cerebral_cortex_entorhinal_cortex.ply': 'right_cerebral_cortex_entorhinal_cortex.ply',
  'right_cerebral_cortex_frontal_lobe.ply': 'right_cerebral_cortex_frontal_lobe.ply',
  'right_cerebral_cortex_occipital_lobe.ply': 'right_cerebral_cortex_occipital_lobe.ply',
  'right_cerebral_cortex_parieto_temporal_lobe.ply': 'right_cerebral_cortex_parieto_temporal_lobe.ply',
  'right_cerebral_peduncle.ply': 'right_cerebral_peduncle.ply',
  'right_colliculus_inferior.ply': 'right_colliculus_inferior.ply',
  'right_colliculus_superior.ply': 'right_colliculus_superior.ply',
  'right_corpus_callosum.ply': 'right_corpus_callosum.ply',
  'right_corticospinal_tract_pyramids.ply': 'right_corticospinal_tract_pyramids.ply',
  'right_cuneate_nucleus.ply': 'right_cuneate_nucleus.ply',
  'right_dentate_gyrus_of_hippocampus.ply': 'right_dentate_gyrus_of_hippocampus.ply',
  'right_facial_nerve_cranial_nerve_7.ply': 'right_facial_nerve_cranial_nerve_7.ply',
  'right_fasciculus_retroflexus.ply': 'right_fasciculus_retroflexus.ply',
  'right_fimbria.ply': 'right_fimbria.ply',
  'right_fornix.ply': 'right_fornix.ply',
  'right_fundus_of_striatum.ply': 'right_fundus_of_striatum.ply',
  'right_globus_pallidus.ply': 'right_globus_pallidus.ply',
  'right_habenular_commissure.ply': 'right_habenular_commissure.ply',
  'right_hippocampus.ply': 'right_hippocampus.ply',
  'right_hypothalamus.ply': 'right_hypothalamus.ply',
  'right_inferior_olivary_complex.ply': 'right_inferior_olivary_complex.ply',
  'right_internal_capsule.ply': 'right_internal_capsule.ply',
  'right_lateral_olfactory_tract.ply': 'right_lateral_olfactory_tract.ply',
  'right_lateral_septum.ply': 'right_lateral_septum.ply',
  'right_lateral_ventricle.ply': 'right_lateral_ventricle.ply',
  'right_mammillary_bodies.ply': 'right_mammillary_bodies.ply',
  'right_mammilothalamic_tract.ply': 'right_mammilothalamic_tract.ply',
  'right_medial_lemniscus_medial_longitudinal_fasciculus.ply': 'right_medial_lemniscus_medial_longitudinal_fasciculus.ply',
  'right_medial_septum.ply': 'right_medial_septum.ply',
  'right_nucleus_accumbens.ply': 'right_nucleus_accumbens.ply',
  'right_olfactory_bulbs.ply': 'right_olfactory_bulbs.ply',
  'right_olfactory_tubercle.ply': 'right_olfactory_tubercle.ply',
  'right_optic_tract.ply': 'right_optic_tract.ply',
  'right_pontine_nucleus.ply': 'right_pontine_nucleus.ply',
  'right_pre_para_subiculum.ply': 'right_pre_para_subiculum.ply',
  'right_stratum_granulosum_of_hippocampus.ply': 'right_stratum_granulosum_of_hippocampus.ply',
  'right_stria_medullaris.ply': 'right_stria_medullaris.ply',
  'right_stria_terminalis.ply': 'right_stria_terminalis.ply',
  'right_striatum.ply': 'right_striatum.ply',
  'right_subependymale_zone_rhinocele.ply': 'right_subependymale_zone_rhinocele.ply',
  'right_superior_olivary_complex.ply': 'right_superior_olivary_complex.ply',
  'right_thalamus.ply': 'right_thalamus.ply',
}


### Tourville atlas ###

# Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
cortAreasIndexMapTourville = {
  'Right-caudalanteriorcingulate': 'Right-caudalanteriorcingulate',
  'Right-caudalmiddlefrontal': 'Right-caudalmiddlefrontal',
  'Right-cuneus': 'Right-cuneus',
  'Right-entorhinal': 'Right-entorhinal',
  'Right-fusiform': 'Right-fusiform',
  'Right-inferiorparietal': 'Right-inferiorparietal',
  'Right-inferiortemporal': 'Right-inferiortemporal',
  'Right-insula': 'Right-insula',
  'Right-isthmuscingulate': 'Right-isthmuscingulate',
  'Right-lateraloccipital': 'Right-lateraloccipital',
  'Right-lateralorbitofrontal': 'Right-lateralorbitofrontal',
  'Right-lingual': 'Right-lingual',
  'Right-medialorbitofrontal': 'Right-medialorbitofrontal',
  'Right-middletemporal': 'Right-middletemporal',
  'Right-paracentral': 'Right-paracentral',
  'Right-parahippocampal': 'Right-parahippocampal',
  'Right-parsopercularis': 'Right-parsopercularis',
  'Right-parsorbitalis': 'Right-parsorbitalis',
  'Right-parstriangularis': 'Right-parstriangularis',
  'Right-pericalcarine': 'Right-pericalcarine',
  'Right-postcentral': 'Right-postcentral',
  'Right-posteriorcingulate': 'Right-posteriorcingulate',
  'Right-precentral': 'Right-precentral',
  'Right-precuneus': 'Right-precuneus',
  'Right-rostralanteriorcingulate': 'Right-rostralanteriorcingulate',
  'Right-rostralmiddlefrontal': 'Right-rostralmiddlefrontal',
  'Right-superiorfrontal': 'Right-superiorfrontal',
  'Right-superiorparietal': 'Right-superiorparietal',
  'Right-superiortemporal': 'Right-superiortemporal',
  'Right-supramarginal': 'Right-supramarginal',
  'Right-transversetemporal': 'Right-transversetemporal',
  'Right-unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray

  'Left-caudalanteriorcingulate': 'Left-caudalanteriorcingulate',
  'Left-caudalmiddlefrontal': 'Left-caudalmiddlefrontal',
  'Left-cuneus': 'Left-cuneus',
  'Left-entorhinal': 'Left-entorhinal',
  'Left-fusiform': 'Left-fusiform',
  'Left-inferiorparietal': 'Left-inferiorparietal',
  'Left-inferiortemporal': 'Left-inferiortemporal',
  'Left-insula': 'Left-insula',
  'Left-isthmuscingulate': 'Left-isthmuscingulate',
  'Left-lateraloccipital': 'Left-lateraloccipital',
  'Left-lateralorbitofrontal': 'Left-lateralorbitofrontal',
  'Left-lingual': 'Left-lingual',
  'Left-medialorbitofrontal': 'Left-medialorbitofrontal',
  'Left-middletemporal': 'Left-middletemporal',
  'Left-paracentral': 'Left-paracentral',
  'Left-parahippocampal': 'Left-parahippocampal',
  'Left-parsopercularis': 'Left-parsopercularis',
  'Left-parsorbitalis': 'Left-parsorbitalis',
  'Left-parstriangularis': 'Left-parstriangularis',
  'Left-pericalcarine': 'Left-pericalcarine',
  'Left-postcentral': 'Left-postcentral',
  'Left-posteriorcingulate': 'Left-posteriorcingulate',
  'Left-precentral': 'Left-precentral',
  'Left-precuneus': 'Left-precuneus',
  'Left-rostralanteriorcingulate': 'Left-rostralanteriorcingulate',
  'Left-rostralmiddlefrontal': 'Left-rostralmiddlefrontal',
  'Left-superiorfrontal': 'Left-superiorfrontal',
  'Left-superiorparietal': 'Left-superiorparietal',
  'Left-superiortemporal': 'Left-superiortemporal',
  'Left-supramarginal': 'Left-supramarginal',
  'Left-transversetemporal': 'Left-transversetemporal',
  'Left-unknown':-1 # this is actually the middle region inside the cortical surface. color it as gray
}




### For Custom ATLAS #####

# MAP from custom atlas to DK. Left-Hand-Side = Blender Regions   Right-Hand-Side = Regions in custom input atlas (.csv INPUT_FILE)
cortAreasIndexMapCustom = {
  'Right-bankssts':-1, # -1 means do not colour this region
  'Right-caudalanteriorcingulate':'Right-anterior cingulate',
  'Right-caudalmiddlefrontal':'Right-medial frontal',
  'Right-cuneus':'Right-cuneus',
  'Right-entorhinal':'Right-entorhinal',
  'Right-frontalpole':'Right-frontal pole',
  'Right-fusiform':'Right-fusiform',
  'Right-inferiorparietal':'Right-angular',
  'Right-inferiortemporal':'Right-inferior temporal',
  'Right-insula':'Right-anterior insula',
  'Right-isthmuscingulate':'Right-posterior cingulate',
  'Right-lateraloccipital':'Right-inferior occipital',
  'Right-lateralorbitofrontal':'Right-medial frontal',
  'Right-lingual':'Right-lingual',
  'Right-medialorbitofrontal':'Right-medial frontal',
  'Right-middletemporal':'Right-middle temporal',
  'Right-paracentral':'Right-precentral',
  'Right-parahippocampal':'Right-parahippocampal',
  'Right-parsopercularis':'Right-central operculum',
  'Right-parsorbitalis':'Right-anterior orbital',
  'Right-parstriangularis':'Right-angular',
  'Right-pericalcarine':'Right-calcarine',
  'Right-postcentral':'Right-postcentral',
  'Right-posteriorcingulate':'Right-posterior cingulate',
  'Right-precentral':'Right-precentral',
  'Right-precuneus':'Right-precuneus',
  'Right-rostralanteriorcingulate':'Right-anterior cingulate',
  'Right-rostralmiddlefrontal':'Right-middle frontal',
  'Right-superiorfrontal':'Right-superior frontal',
  'Right-superiorparietal':'Right-superior parietal',
  'Right-superiortemporal':'Right-superior temporal',
  'Right-supramarginal':'Right-supramarginal',
  'Right-temporalpole':'Right-temporal pole',
  'Right-transversetemporal':'Right-planum temporale',
  'Right-unknown':-1, # this is actually the middle region inside the cortical surface. color it as gray

  'Left-bankssts':-1, # -1 means do not colour this region
  'Left-caudalanteriorcingulate':'Left-anterior cingulate',
  'Left-caudalmiddlefrontal':'Left-medial frontal',
  'Left-cuneus':'Left-cuneus',
  'Left-entorhinal':'Left-entorhinal',
  'Left-frontalpole':'Left-frontal pole',
  'Left-fusiform':'Left-fusiform',
  'Left-inferiorparietal':'Left-angular',
  'Left-inferiortemporal':'Left-inferior temporal',
  'Left-insula':'Left-anterior insula',
  'Left-isthmuscingulate':'Left-posterior cingulate',
  'Left-lateraloccipital':'Left-inferior occipital',
  'Left-lateralorbitofrontal':'Left-medial frontal',
  'Left-lingual':'Left-lingual',
  'Left-medialorbitofrontal':'Left-medial frontal',
  'Left-middletemporal':'Left-middle temporal',
  'Left-paracentral':'Left-precentral',
  'Left-parahippocampal':'Left-parahippocampal',
  'Left-parsopercularis':'Left-central operculum',
  'Left-parsorbitalis':'Left-anterior orbital',
  'Left-parstriangularis':'Left-angular',
  'Left-pericalcarine':'Left-calcarine',
  'Left-postcentral':'Left-postcentral',
  'Left-posteriorcingulate':'Left-posterior cingulate',
  'Left-precentral':'Left-precentral',
  'Left-precuneus':'Left-precuneus',
  'Left-rostralanteriorcingulate':'Left-anterior cingulate',
  'Left-rostralmiddlefrontal':'Left-middle frontal',
  'Left-superiorfrontal':'Left-superior frontal',
  'Left-superiorparietal':'Left-superior parietal',
  'Left-superiortemporal':'Left-superior temporal',
  'Left-supramarginal':'Left-supramarginal',
  'Left-temporalpole':'Left-temporal pole',
  'Left-transversetemporal':'Left-planum temporale',
  'Left-unknown':-1 # this is actually the middle region inside the cortical surface. color it as gray
}


# Subcortical areas
# this map is used by all atlases (DK, Destrieux, Tourville)
subcortAreasIndexMap = {
  'Left-Accumbens-area': 'Left-Accumbens-area', # -1 means do not colour this region
  'Left-Caudate': 'Left-Caudate',
  'Left-Cerebellum-White-Matter': 'Left-Cerebellum-White-Matter',
  'Left-Inf-Lat-Vent': 'Left-Inf-Lat-Vent',
  'Left-Pallidum': 'Left-Pallidum',
  'Left-Thalamus-Proper': 'Left-Thalamus-Proper',
  'Left-Amygdala': 'Left-Amygdala',
  'Left-Cerebellum-Cortex': 'Left-Cerebellum-Cortex',
  'Left-Hippocampus': 'Left-Hippocampus',
  'Left-Lateral-Ventricle': 'Left-Lateral-Ventricle',
  'Left-Putamen': 'Left-Putamen',
  'Left-VentralDC': 'Left-VentralDC', 

  'Right-Accumbens-area': 'Right-Accumbens-area', # -1 means do not colour this region
  'Right-Caudate': 'Right-Caudate',
  'Right-Cerebellum-White-Matter': 'Right-Cerebellum-White-Matter',
  'Right-Inf-Lat-Vent': 'Right-Inf-Lat-Vent',
  'Right-Pallidum': 'Right-Pallidum',
  'Right-Thalamus-Proper': 'Right-Thalamus-Proper',
  'Right-Amygdala': 'Right-Amygdala',
  'Right-Cerebellum-Cortex': 'Right-Cerebellum-Cortex',
  'Right-Hippocampus': 'Right-Hippocampus',
  'Right-Lateral-Ventricle': 'Right-Lateral-Ventricle',
  'Right-Putamen': 'Right-Putamen',
  'Right-VentralDC': 'Right-VentralDC'
  }


subcortAreasIndexMapCustom = {
  'Left-Accumbens-area':'Left-Accumbens-area', # -1 means do not colour this region
  'Left-Caudate':'Left-Caudate',
  'Left-Cerebellum-White-Matter':-1,
  'Left-Inf-Lat-Vent':-1,
  'Left-Pallidum':'Left-Pallidum',
  'Left-Thalamus-Proper':'Left-Thalamus',
  'Left-Amygdala':'Left-Amygdala',
  'Left-Cerebellum-Cortex':-1,
  'Left-Hippocampus':'Left-Hippocampus',
  'Left-Lateral-Ventricle':-1,
  'Left-Putamen':'Left-Putamen',
  'Left-VentralDC':'Left-VentralDC',

  'Right-Accumbens-area':'Right-Accumbens-area', # -1 means do not colour this region
  'Right-Caudate':'Right-Caudate',
  'Right-Cerebellum-White-Matter':-1,
  'Right-Inf-Lat-Vent':-1,
  'Right-Pallidum':'Right-Pallidum',
  'Right-Thalamus-Proper':'Right-Thalamus',
  'Right-Amygdala':'Right-Amygdala',
  'Right-Cerebellum-Cortex':-1,
  'Right-Hippocampus':'Right-Hippocampus',
  'Right-Lateral-Ventricle':-1,
  'Right-Putamen':'Right-Putamen',
  'Right-VentralDC':'Right-VentralDC'
}
